### PR TITLE
fix: Now you can't type more than 255 characters in the bio field of user settings

### LINKED ISSUE #2612: Bug: Can keep typing in the bio field of user settings after 255 characters
We currently display a message saying the bio is too long in the user settings, but we're not leveraging the native [maxLength](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/maxlength) HTML attribute to prevent someone from typing past the limit.

CleanShot 2024-02-07 at 08 15 24

As well, since `maxLength` prevents you from typing or pasting text past 255 characters, the `bio too long` message will actually never appear so it can be removed from the component.

This is what happens when `maxLength="255"` is set.

CleanShot 2024-02-07 at 08 08 43

### PR DESCRIPTION
**Pull request by Pagla-Dasu**
Now, it Can't keep typing in the bio field of user settings after 255 characters. Changed the code in user-sttings-page.tsx

fix #2612

## Description

This PR fixes the issue #2612 fixing the maximum character issue of 255 characters.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Please use this format link issue numbers: Fixes #2612 
https://github.com/open-sauced/app/issues/2612 

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/organisms/UserSettingsPage/user-settings-page.tsx [hunk 1]
```diff
@@ -281,20 +281,15 @@ const UserSettingsPage = ({ user }: UserSettingsPageProps) => {
...
-              {bio?.length > 255 ? (
-                <p aria-live="assertive" className="text-light-red-10 text-xs">
-                  Bio too long
-                </p>
-              ) : (
-                <p aria-live="polite" className="text-xs">
-                  {bio?.length}/255
-                </p>
-              )}
+              <p aria-live="polite" className="text-xs">
```
Comment (nickytonline) [inline components/organisms/UserSettingsPage/user-settings-page.tsx:290]: @BekahHW do you think being unable to type further and seeing `255/255` in the UI is clear enough? If not we can put a message along the lines of max length of bio reached when they hit 255 characters. The browser won't allow anymore characters because of the `maxLength` here which is what I proposed in the good first issue linked to this PR.

**Review by nickytonline — COMMENTED** [review]
Thanks for the PR @Pagla-Dasu! Just getting some feedback from my co-worker about the fix I proposed for this issue.

**Comment by Pagla-Dasu** [comment]
@nickytonline you're welcome 👍🏼

**Comment by Pagla-Dasu** [comment]
@nickytonline , Any update on the PR?

**Comment by nickytonline** [comment]
There are failures because of linting/prettier.

```
./components/organisms/UserSettingsPage/user-settings-page.tsx
284:30  Error: Replace `·=·` with `=`  prettier/prettier
2[91](https://github.com/open-sauced/app/actions/runs/7821446623/job/21339420324?pr=2615#step:6:92):1  Error: Replace `+················{bio?.length}/255⏎+` with `················+·{bio?.length}/255·+{"·"}⏎·`  prettier/prettier
```

run `npm lint -- --fix` to fix that.

**Comment by Pagla-Dasu** [comment]
@nickytonline , The prettier issue is fixed, you can now merge the code.

File: components/organisms/UserSettingsPage/user-settings-page.tsx (hunk 1 above)
Comment (BekahHW) [reply components/organisms/UserSettingsPage/user-settings-page.tsx:290]: Sorry, idk how I missed this.

We could put a message there, but I think the highlight one is too much here bc the input is so small.

This is what it currently looks like when it's too long:

image

What if we keep the 255/255 and have a message that says Bio Max Length underneath?

Comment (nickytonline) [reply components/organisms/UserSettingsPage/user-settings-page.tsx:292]: Did we decide on something for this @BekahHW?

Comment (BekahHW) [reply components/organisms/UserSettingsPage/user-settings-page.tsx:292]: @nickytonline I think my last suggestion is the way to go.

255/255 in red
Message: Bio Max Length in red

**Review by BekahHW — CHANGES_REQUESTED** [review]
A couple of things:

1. Let's add the message if the bio hits max
2. There's something going on with '+' signs here. Let's make sure those are removed.

image

**Comment by BekahHW** [comment]
@Pagla-Dasu how are things going here?

**Comment by Pagla-Dasu** [comment]
> @Pagla-Dasu how are things going here?

oh, I am so sorry @BekahHW, I missed your request for those changes. Will get that done asap.

**Comment by Pagla-Dasu** [comment]
@nickytonline @BekahHW, do check the commit. The changes are made accordingly.

**Comment by jpmcb** [comment]
cc @open-sauced/engineering let's have a look at this and clean up long standing PRs 🙏🏼

**Review by jpmcb — APPROVED** [review]
LGTM! :shipit:
