### PR TITLE
fix: now search dialog is always on top of other elements

### LINKED ISSUE #3614: Bug: Mobile screen does not respect the command palette blur
## mobile
Screenshot 2024-06-21 at 2 17 09 PM

## desktop
Screenshot 2024-06-21 at 2 17 04 PM

### Steps to reproduce

View on mobile and note the logo and some chart elements are not blurred.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now search dialog is always on top of other elements. I'm just going to adjust the overlay to the color it was originally (more white).

## Related Tickets & Documents

Fixes #3614

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-08-27 at 15 16 22

**After**

CleanShot 2024-08-27 at 16 11 46

## Steps to QA

1. Go to a repository page, e.g. /s/kubernetes/kubernetes
2. Open the search dialog. Notice the logo as well as other graphs no longer bleed through the search bar or the overlay.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

File: components/organisms/SearchDialog/search-dialog.tsx [hunk 1]
```diff
@@ -136,50 +138,68 @@ const SearchDialog = () => {
...
-      <div className="absolute w-full h-full left-0 top-0 z-50 backdrop-blur-sm" onClick={() => setOpenSearch(false)} />
-      <div
-        className="flex flex-col w-full max-w-2xl h-fit max-h-full bg-white shadow-xl border transition rounded-lg ring-light-slate-6 relative z-50 overflow-hidden"
-        onMouseMove={() => cursor !== -1 && setCursor(-1)}
-      >
-        <div className="flex w-full h-full items-center border-b p-2 pl-3">
-          {isSearching ? (
-            <div className="flex-none w-4 h-4 rounded-full border-2 border-light-slate-9 border-b-light-slate-5 border-r-light-slate-5 animate-spin" />
-          ) : (
+    <Dialog open={openSearch} onOpenChange={setOpenSearch}>
```
Comment (nickytonline) [inline components/organisms/SearchDialog/search-dialog.tsx:141]: It looks like more changes than it is, but TLDR; the content is wrapped in a ` <Dialog />` component now.

**Review by brandonroberts — APPROVED** [review]

**Review by jpmcb — APPROVED** [review]

**Review by zeucapua — APPROVED** [review]
