### PR TITLE
fix: Added state for reactions dropdown on highlight cards.

### LINKED ISSUE #2408: Bug: Reaction icons are closing right away when clicking the smiley button on the highlight card mode
### Describe the bug

When I wanted to give a reaction to a highlight, the icon shuts down right away (in milliseconds) every time I click it.

Below is the screen recording. It's hard to capture the state of the icon closing right away, so you might see as if nothing happens when clicking the icon button.

icon highlights

 

### Steps to reproduce

1. Click the bell icon on the top bar of your OpenSauced dashboard to open the notifications.
2. Click on a user's highlight. You will see the highlight's card.
3. Click the smiley button to give reaction to the highlight.
4. The icons will close immediately.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by aryanas159**
## Description
fixes #2408 

I have added a state for the reactions dropdown which checks whether the dropdown is open or closed.
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/114330931/8ed3cfc2-51ba-499d-b8bd-3424b3fe3358

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?
SimpleGIF

### CODE REVIEW

**Review by nickytonline — APPROVED** [review]
Thanks for the fix @aryanas159! :shipit:

File: components/molecules/ContributorHighlight/contributor-highlight-card.tsx [hunk 1]
```diff
@@ -620,12 +621,18 @@ const ContributorHighlightCard = ({
       )}
 
       <div className="flex flex-wrap items-center gap-1">
-        <DropdownMenu modal={false}>
-          <DropdownMenuTrigger className="p-1   rounded-full data-[state=open]:bg-light-slate-7">
+        <DropdownMenu modal={false} open={emojiDropdownOpen}>
+          <DropdownMenuTrigger
+            className="p-1   rounded-full data-[state=open]:bg-light-slate-7"
```
Comment (NsdHSO) [inline components/molecules/ContributorHighlight/contributor-highlight-card.tsx:626]:
```suggestion
            className="p-1 rounded-full data-[state=open]:bg-light-slate-7"
```

**Review by NsdHSO — APPROVED** [review]
LGTM
