### PR TITLE
fix: now workspace top nav link works as expected

### LINKED ISSUE #2789: Bug: / redirect to last accessed workspace never works from top navigation
It was discovered that if you weren't onboarded we always redirected to /feed from / so the redirect to the last accessed workspace would never happen.

Discussed with @isabensusan and @brandonroberts and the fix is to no longer redirect to /feed if you haven't onboarded.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

It was discovered that if you weren't onboarded we always redirected to `/feed` from `/` so the redirect to the last accessed workspace would never happen.

Now we no longer redirect to `/feed` if you haven't onboarded.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2789

## Steps to QA

1. Log in
2. Click on the Workspace link in the top nav.
3. You're redirected to the last accessed workspace, even if you haven't completed onboarding.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: middleware.ts [hunk 1]
```diff
@@ -113,14 +113,9 @@ export async function middleware(req: NextRequest) {
...
+      const workspaceUrl = getWorkspaceUrl(req.cookies, req.url, data.personal_workspace_id);
 
-      if (data.is_onboarded) {
-        const workspaceUrl = getWorkspaceUrl(req.cookies, req.url, data.personal_workspace_id);
-
-        return NextResponse.redirect(`${workspaceUrl}`);
-      } else {
-        return NextResponse.redirect(new URL("/feed", req.url));
-      }
+      return NextResponse.redirect(`${workspaceUrl}`);
```
Comment (nickytonline) [inline middleware.ts:118]: We no longer redirect to `/feed` if you're not onboarded.

**Review by brandonroberts — APPROVED** [review]

**Review by jpmcb — APPROVED** [review]

**Comment by isabensusan** [comment]
image

**Review by isabensusan — APPROVED** [review]
