### PR TITLE
fix: now the page is cached varying on the day range

### LINKED ISSUE #3311: Bug: OG images for repository pages are always cached as the 30 day range image
OG images for repository pages are always cached as the 30 day range image. The caching needs to vary on the `range` query parameter.

Note this does not affect the data loaded on the page as that's all loaded client-side for the given day range.

30 day range

CleanShot 2024-05-03 at 08 58 23

90 day range

CleanShot 2024-05-03 at 08 58 57

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now cached repository pages vary on the range query parameter. I've also added a cache tag for repository pages and individual repository pages if we ever need to purge them.

Note the actual page loads the correct data for the given day range. It's only OG images that were affected.

## Related Tickets & Documents

Relates to #3278
Fixes #3311

## Mobile & Desktop Screenshots/Recordings

**Before**

30 day range

CleanShot 2024-05-03 at 08 58 23

90 day range

CleanShot 2024-05-03 at 08 58 57

**After**

30 day range

CleanShot 2024-05-03 at 08 56 43

90 day range

CleanShot 2024-05-03 at 08 57 46

## Steps to QA

1. Go to https://deploy-preview-3310--oss-insights.netlify.app/s/open-sauced/app
2. Open the dev tools and look at the OG image URL. It's for the 30 day range. `https://deploy-preview-3310--oss-insights.netlify.app/og-images/repository/open-sauced/app/30?description=%F0%9F%8D%95+The+path+to+your+next+contribution.`
3. Go to https://deploy-preview-3310--oss-insights.netlify.app/s/open-sauced/app?range=90
4. Open the dev tools and look at the OG image URL. Notice the link is for 90 days and no longer the 30 day range, i.e. `https://deploy-preview-3310--oss-insights.netlify.app/og-images/repository/open-sauced/app/90?description=%F0%9F%8D%95+The+path+to+your+next+contribution.`

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

File: pages/s/[org]/[repo]/index.tsx [hunk 1]
```diff
@@ -55,6 +55,8 @@ export async function getServerSideProps(context: GetServerSidePropsContext) {
 
   // Cache for two hours
   context.res.setHeader("Netlify-CDN-Cache-Control", "public, max-age=0, stale-while-revalidate=7200");
+  context.res.setHeader("Netlify-Vary", "query=range");
```
Comment (nickytonline) [inline pages/s/[org]/[repo]/index.tsx:58]: This change isn't because the page will load incorrectly for the given day range. That info is all loaded client-side. This fixes the OG image that will get cached for the page. Now it will [vary the cache](https://www.netlify.com/blog/netlify-cache-key-variations/#query) so the correct OG image link is generated for the given day range.

File: pages/s/[org]/[repo]/index.tsx [hunk 2]
```diff
@@ -55,6 +55,8 @@ export async function getServerSideProps(context: GetServerSidePropsContext) {
...
+  context.res.setHeader("Cache-Tag", `repo-pages,repo-page-${repoData.id}`);
```
Comment (nickytonline) [inline pages/s/[org]/[repo]/index.tsx:59]: I added this because it will give us the ability to purge all repository pages from the cache (if needed) or on an individual basis. For more info about this see [Cache-tags & Purge API on Netlify](https://www.netlify.com/blog/cache-tags-and-purge-api-on-netlify/).

**Review by brandonroberts — APPROVED** [review]

**Review by jpmcb — APPROVED** [review]
🧺🏀
