### PR TITLE
fix: now StarSearch for workspaces only works for editors

### LINKED ISSUE #3640: Bug: StarSearch in Workspaces won't work if you're not part of a Workspace
### Describe the bug

When trying to use StarSearch in a Workspace I get the "I am a chat bot that highlights open source contributors" error message.

image

We should probably have a disabled state for StarSearch and replace the tooltip content to "You can only use StarSearch in Workspaces you are a member of"

image

In addition to this, we should add a disclaimer to the StarSearch widget response with the same message

### Steps to reproduce

1. Go to any Workspace you are not a member/owner of
2. Open the StarSearch widget
3. Try any of the example prompts and see that it will not work

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now if a user is not an editor of a workspace, the tooltip of the StarSearch CTA for workspaces will reflect that along with the button changing to a grey scale. As well, now if logged out, the StarSearch for workspaces CTA will be visible and enabled so you can log in to use it. The button also will be set to `aria-disabled="true"` if they do not have access to StarSearch as well as button text indicating so.

## Related Tickets & Documents

Fixes #3640

## Mobile & Desktop Screenshots/Recordings

https://github.com/user-attachments/assets/35b367df-d08c-4433-9880-630e74211576

**Not an editor**

CleanShot 2024-07-17 at 17 26 44

**Is an editor**

CleanShot 2024-07-17 at 17 30 31

**Logged out**

CleanShot 2024-07-17 at 17 28 22

## Steps to QA

Logged out

1. Go to a workspace
2. Notice the StarSearch CTA in the bottom right
3. It says in the tooltip that you need to be signed in to use workspaces
4. Click the CTA
5. You're logged in and either have access to StarSearch for workspaces (you're an editor), or it's grayed a bit telling you you're not an editor.

Logged in

1. You're logged in and either have access to StarSearch for the current worksapce (you're an editor), or it's grayed a bit telling you you're not an editor.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

File: components/StarSearch/ChatAvatar.tsx [hunk 1]
```diff
@@ -5,7 +5,7 @@ type Author = "You" | "StarSearch" | "Guest";
 
 interface ChatAvatarProps {
   author: Author;
-  userId?: number;
+  userId?: number | null;
```
Comment (nickytonline) [inline components/StarSearch/ChatAvatar.tsx:8]: This change was made because we're getting the user ID client-side now and `useSupabaseAuth` can return null for a `userId`.

File: components/StarSearch/StarSearchButton.tsx [hunk 2]
```diff
@@ -1,23 +1,27 @@
 import { useLocalStorage } from "react-use";
+import clsx from "clsx";
 import Tooltip from "components/atoms/Tooltip/tooltip";
 import { StarSearchLogo } from "./StarSearchLogo";
 
 interface StarSearchButtonProps {
   onOpen: (e: React.MouseEvent<HTMLButtonElement>) => void;
+  tooltipText: string;
+  enabled: boolean;
```
Comment (nickytonline) [inline components/StarSearch/StarSearchButton.tsx:9]: `tooltipText` is a prop now so that we can indicate whether they have access to StarSearch or not, or if they need to log in first.

`enabled` is a prop as well now, for the above reasons.

File: components/StarSearch/StarSearchEmbed.tsx [hunk 3]
```diff
@@ -52,13 +56,29 @@ export const StarSearchEmbed = ({
...
+    ? "You need to be an editor to use StarSearch"
+    : "Sign in to use StarSearch";
+
   return (
     <>
       <div className="fixed bottom-0 right-0 flex justify-end p-2">
         <StarSearchButton
           onOpen={() => {
-            setDrawerOpen(true);
+            if (!userId) {
```
Comment (nickytonline) [inline components/StarSearch/StarSearchEmbed.tsx:72]: They're not logged in, so we'll log them in.

File: components/Workspaces/WorkspaceWelcomeModal.tsx [hunk 4]
```diff
@@ -81,7 +81,7 @@ export default function WorkspaceWelcomeModal({ isOpen, onClose }: WorkspaceWelc
     </Drawer>
   ) : (
     <Dialog open={isOpen}>
-      <DialogContent autoStyle={false} onEscapeKeyDown={onClose} onPointerDownOutside={onClose}>
+      <DialogContent aria-label={TITLE} autoStyle={false} onEscapeKeyDown={onClose} onPointerDownOutside={onClose}>
```
Comment (nickytonline) [inline components/Workspaces/WorkspaceWelcomeModal.tsx:84]: makes the dialog more accessible and also helps with E2E tests for locating the dialog.

File: pages/workspaces/[workspaceId]/activity.tsx [hunk 5]
```diff
@@ -22,10 +22,13 @@ import WorkspaceBanner from "components/Workspaces/WorkspaceBanner";
...
 import { StarSearchEmbed } from "components/StarSearch/StarSearchEmbed";
 import { useMediaQuery } from "lib/hooks/useMediaQuery";
-import { FeatureFlag, getAllFeatureFlags } from "lib/utils/server/feature-flags";
 import { WORKSPACE_STARSEARCH_SUGGESTIONS } from "lib/utils/star-search";
+import useSupabaseAuth from "lib/hooks/useSupabaseAuth";
+import { useWorkspaceMembers } from "lib/hooks/api/useWorkspaceMembers";
 
-const InsightUpgradeModal = dynamic(() => import("components/Workspaces/InsightUpgradeModal"));
+const InsightUpgradeModal = dynamic(() => import("components/Workspaces/InsightUpgradeModal"), {
+  ssr: false,
```
Comment (nickytonline) [inline pages/workspaces/[workspaceId]/activity.tsx:30]: Don't need to server-side render this. as it's a modal that might never get used, so load it client-side.

File: pages/workspaces/[workspaceId]/activity.tsx [hunk 6]
```diff
@@ -63,32 +54,36 @@ export const getServerSideProps = async (context: GetServerSidePropsContext) =>
...
-const WorkspaceActivityPage = ({
-  workspace,
-  isOwner,
-  overLimit,
-  bearerToken,
-  userId,
-  featureFlags,
-}: WorkspaceDashboardProps) => {
+const WorkspaceActivityPage = ({ workspace, overLimit }: WorkspaceDashboardProps) => {
+  const { sessionToken, signIn, userId } = useSupabaseAuth();
```
Comment (nickytonline) [inline pages/workspaces/[workspaceId]/activity.tsx:74]: This page, the activity pages (pull requests, issues) load the user info client-side now because when you log in if you were logged out, the page does not rerun getServerSideProps and rerender server-side, so we need to handle this client-side. That would probably change if/when we move to Next.js's app router.

File: pages/workspaces/[workspaceId]/activity.tsx [hunk 7]
```diff
@@ -153,7 +148,7 @@ const WorkspaceActivityPage = ({
                   selectedTab={"pull requests"}
                   pageId={`/workspaces/${workspace.id}`}
                 />
-                {isMobile ? <DayRangePicker /> : null}
+                <ClientOnly>{isMobile ? <DayRangePicker /> : null}</ClientOnly>
```
Comment (nickytonline) [inline pages/workspaces/[workspaceId]/activity.tsx:151]: Hydration error fixes. These were preventing me from running the changes to E2E tests.

File: pages/workspaces/[workspaceId]/activity.tsx [hunk 8]
```diff
@@ -163,32 +158,36 @@ const WorkspaceActivityPage = ({
...
       </WorkspaceLayout>
-      <StarSearchEmbed
-        userId={userId}
-        bearerToken={bearerToken}
-        suggestions={WORKSPACE_STARSEARCH_SUGGESTIONS}
-        isMobile={isMobile}
-        // TODO: implement once we have shared chats in workspaces
-        sharedChatId={null}
-        tagline="Ask anything about your workspace"
+      <ClientOnly>
```
Comment (nickytonline) [inline pages/workspaces/[workspaceId]/activity.tsx:171]: This could be a dynamic import that loads client-side only but I noticed if it takes a while for data to load in grids client-side, it delays the loading of this, so I decided to keep it part of the server-side render.

File: pages/workspaces/[workspaceId]/issues.tsx [hunk 9]
```diff
@@ -164,6 +170,20 @@ const WorkspaceIssuesPage = ({ workspace, isOwner, overLimit }: WorkspaceDashboa
           />
         </div>
       </WorkspaceLayout>
+      <ClientOnly>
+        <StarSearchEmbed
```
Comment (nickytonline) [inline pages/workspaces/[workspaceId]/issues.tsx:174]: StarSearch for workspaces was missing from the activity issues page.

**Review by jpmcb — APPROVED** [review]
Works well! Nice!

**Review by brandonroberts — APPROVED** [review]
