### PR TITLE
fix: use a tags instead of link tags

### LINKED ISSUE #4108: Bug: loading dev card page from the user profile crashes
Going to the dev card page directly works, but if you click on the dev card button near the avatar on the user profile page, it crashes.

CleanShot 2024-09-18 at 08 17 58

CleanShot 2024-09-18 at 08 20 19

The `user` is `null` causing the crash.

### PR DESCRIPTION
**Pull request by Bashamega**
## Description

Fixed the bug by using a tags instead of link tags

## Related Tickets & Documents

Fixes #4108 

## Mobile & Desktop Screenshots/Recordings

https://github.com/user-attachments/assets/2310dc7d-f281-4dd5-ad5f-3629c0309d6b

### CODE REVIEW

File: components/molecules/ContributorProfileHeader/contributor-profile-header.tsx [hunk 1]
```diff
@@ -156,14 +156,14 @@ const ContributorProfileHeader = ({
           />
 
           <Tooltip content="Get dev card">
-            <Link
+            <a
```
Comment (nickytonline) [inline components/molecules/ContributorProfileHeader/contributor-profile-header.tsx:159]: Although we lose the SPA like mode by going to an anchor, this is better and it's only one page navigation.

**Review by nickytonline — APPROVED** [review]
Thanks @Bashamega!
