### PR TITLE
fix: now unauthenticated users can access public workspaces

### LINKED ISSUE #2773: Bug: public workspaces for unauthenticated users re-routes to the feed
### Describe the bug

When I go to a public workspace URL (like https://beta.app.opensauced.pizza/workspaces/25924332-18f1-46be-b1b1-c935dd01720c/repositories), it redirects to the feed if I'm an unauthenticated user (note the redirect in the url)

Screenshot 2024-02-26 at 12 14 18 PM

_But_, if I'm an authenticated user, I can go to that public workspace (note my test user here)

Screenshot 2024-02-26 at 12 13 26 PM

---

I'd expect public workspaces to work for _all_ types of users, including unauthenticated ones

### Steps to reproduce

1. Go to a public workspace when logged out
2. See redirect

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now unauthenticate users can acess public workspaces.

**There will be a follow up PR to fix the UI for the app sidebar so that people can't attempt to create new insights, or a new workspace.**

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2773

## Steps to QA

1. Logged out, go to the public workspace https://beta.app.opensauced.pizza/workspaces/a9b404dc-528a-4feb-802c-c266f4e356db/repositories
2. The workspace loads

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: pages/workspaces/new.tsx [hunk 1]
```diff
@@ -10,6 +12,23 @@ import { TrackedReposTable } from "components/Workspaces/TrackedReposTable";
 import { createWorkspace } from "lib/utils/workspace-utils";
 import { WORKSPACE_UPDATED_EVENT } from "components/shared/AppSidebar/AppSidebar";
 
+export const getServerSideProps = async (context: GetServerSidePropsContext) => {
```
Comment (nickytonline) [inline pages/workspaces/new.tsx:15]: Need to guard against someone unauthenticate trying to create a workspace. This wasn't an issue before because unauthenticated users couldn't hit this route.

**Review by brandonroberts — APPROVED** [review]

**Review by jpmcb — APPROVED** [review]
