### PR TITLE
fix: add accessibility features to footer component

### LINKED ISSUE #2037: bug: accessibility enhancement for footer component
### Describe the bug

The Footer component in the app currently lacks essential accessibility features, making it challenging for users with disabilities to navigate and comprehend the content. This issue is created to address these accessibility concerns.

The primary accessibility issues in the Footer component are as follows:

- The brand logo lacks an accessible text alternative (alt).
- Some links do not have descriptive text, making their purpose unclear to screen reader users.
- Social media icons are missing accessible descriptions.
- The colour contrast in the footer does not meet accessibility standards.

### Proposed Solution

To make the Footer component more accessible, the following actions should be taken:

- Add an `alt` attribute to the brand logo's `Image` component with a descriptive text alternative.
- Provide descriptive text for links to make their purpose clear to screen reader users.
- Include accessible descriptions for social media icons using `aria-label` attributes.
- Improve colour contrast by adjusting text styling or background colour.

### Expected Outcome

After implementing the proposed accessibility improvements, we expect the Footer component to be more inclusive and user-friendly.

### Steps to reproduce

1. Go to 'https://app.opensauced.pizza/user/notifications?filter=all'
2. Scroll to the bottom.
3. Check the social icons.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by RitaDee**
## Description

This PR enhances the accessibility of the footer component in the app by adding accessible labels to links and social media icons. This update ensures that the footer is more usable for all users, including those who rely on screen readers.

**Changes Made:**
- Added `aria-label` attributes to all links in the footer to provide descriptive labels for screen reader users, ensuring they understand the purpose of each link.
- Implemented a function, `getSocialMediaPlatformName`, to dynamically generate accessible labels for social media icons based on the platform they link to.
- Included relevant platform names in the `aria-label` attributes for social media icons.
- Enhanced the overall accessibility of the footer component to meet accessibility standards.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [x] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2037

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/organisms/Footer/footer.tsx [hunk 1]
```diff
@@ -58,12 +58,30 @@ const footerContext = [
 ];
 
 const Footer = (): JSX.Element => {
+  function getSocialMediaPlatformName(url: string) {
+    if (url.includes("twitter.com")) {
```
Comment (OgDev-01) [inline components/organisms/Footer/footer.tsx:62]: non-blocking: but i think a switch case would be more cleaner and readable

File: components/organisms/Footer/footer.tsx [hunk 2]
```diff
@@ -58,12 +58,39 @@ const footerContext = [
...
+      case url.includes("youtube.com"):
+        platform = "YouTube";
+        break;
+      case url.includes("discord.com"):
+        platform = "Discord";
+        break;
+      case url.includes("dev.to"):
+        platform = "Dev.to";
+        break;
+    }
```
Comment (OgDev-01) [inline components/organisms/Footer/footer.tsx:83]:
```suggestion
   let platform;

    switch (true) {
      case url.includes("twitter.com"):
        platform = "Twitter";
        break;
      case url.includes("github.com"):
        platform = "GitHub";
        break;
      case url.includes("instagram.com"):
        platform = "Instagram";
        break;
      case url.includes("youtube.com"):
        platform = "YouTube";
        break;
      case url.includes("discord.com"):
        platform = "Discord";
        break;
      case url.includes("dev.to"):
        platform = "Dev.to";
        break;
      default:
        platform = "Social Media";
    }
```

**Review by OgDev-01 — CHANGES_REQUESTED** [review]
add a default fallback to switch

File: components/organisms/Footer/footer.tsx [hunk 3]
```diff
@@ -58,12 +58,41 @@ const footerContext = [
 ];
 
 const Footer = (): JSX.Element => {
+  function getSocialMediaPlatformName(url: string) {
+    let platform = "Social Media";
```
[the remark this answers is not in the document]
Comment (RitaDee) [reply components/organisms/Footer/footer.tsx:62]: Okay

**Review by OgDev-01 — APPROVED** [review]
Great!! 👏👏👏👏👏

**Comment by RitaDee** [comment]
> Great!! 👏👏👏👏👏

😄 Merci

File: components/organisms/Footer/footer.tsx [hunk 4]
```diff
@@ -58,12 +58,31 @@ const footerContext = [
...
+        return "YouTube";
+      case url.includes("discord.com"):
+        return "Discord";
+      case url.includes("dev.to"):
+        return "Dev.to";
+      default:
+        return "Social Media";
+    }
+  }
+
```
Comment (nickytonline) [inline components/organisms/Footer/footer.tsx:79]: Refactor (blocking): No need to have a function for this. Just hard code the names in the links below, e.g.

```html
            <a
              target="_blank"
              href={url}
              key={index}
              rel="noopener noreferrer"
              aria-label={`Visit our Dev.to profile`}
            >
...
```

**Review by nickytonline — CHANGES_REQUESTED** [review]
Thanks for making the footer links more accessible @RitaDee! Just a couple of changes and then this is good to merge.

File: components/organisms/Footer/footer.tsx (hunk 4 above)
Comment (RitaDee) [reply components/organisms/Footer/footer.tsx:79]: > Refactor (blocking): No need to have a function for this. Just hard code the names in the links below, e.g.

Thank you for your feedback. I understand your point, and I initially considered hard-coding the social media names in the links. In this specific code block, we are mapping through the 'socials' array, which contains various social media profiles. 

Each profile has a unique URL and icon, and we want to provide accessible labels that accurately represent each profile.

```
{footerContext[2].socials?.map(({ url, icon }, index) => (
            <a
              target="_blank"
              href={url}
              key={index}
              rel="noopener noreferrer"
              aria-label={`Visit our ${getSocialMediaPlatformName(url)} profile`}
            >
              {icon}
            </a>
          ))}
```

By using the 'getSocialMediaPlatformName' function, we ensure that the accessibility labels are dynamically generated based on the specific social media URL being linked. This allows us to maintain consistency between the labels and URLs while accommodating future changes to our social media profiles.

Please let me know your thoughts.

Comment (RitaDee) [reply components/organisms/Footer/footer.tsx:79]: > > Refactor (blocking): No need to have a function for this. Just hard code the names in the links below, e.g.
> 
> Thank you for your feedback. I understand your point, and I initially considered hard-coding the social media names in the links. In this specific code block, we are mapping through the 'socials' array, which contains various social media profiles.
> 
> Each profile has a unique URL and icon, and we want to provide accessible labels that accurately represent each profile.
> 
> ```
> {footerContext[2].socials?.map(({ url, icon }, index) => (
>             <a
>               target="_blank"
>               href={url}
>               key={index}
>               rel="noopener noreferrer"
>               aria-label={`Visit our ${getSocialMediaPlatformName(url)} profile`}
>             >
>               {icon}
>             </a>
>           ))}
> ```
> 
> By using the 'getSocialMediaPlatformName' function, we ensure that the accessibility labels are dynamically generated based on the specific social media URL being linked. This allows us to maintain consistency between the labels and URLs while accommodating future changes to our social media profiles, this approach keeps our code DRY (Don't Repeat Yourself) and maintainable.
> 
> Please let me know your thoughts.

Comment (nickytonline) [reply components/organisms/Footer/footer.tsx:79]: I'm just seeing how that page was originally implemented, i.e. `footerContext`. Instead of `getSocialMediaPlatformName(url)`, add the label text to the `footerContext` directly.

```
footerContext = [
...
{
    socials: [
      {
        url: "https://twitter.com/saucedopen",
        icon: <FaXTwitter className="text-2xl hover:text-light-slate-10  text-light-slate-9" />,
				label: "OpenSauced on Twitter"
      },
			....
    ],
  },
```

and then in the JSX:

```jsx
          {footerContext[2].socials?.map(({ url, icon, label }, index) => (
            <a target="_blank" aria=label={label} href={url} key={index} rel="noopener noreferrer">
              {icon}
            </a>
          ))}
```

Comment (OgDev-01) [reply components/organisms/Footer/footer.tsx:79]: +1 on this @nickytonline, it would be more cleaner this way 👍

Comment (RitaDee) [reply components/organisms/Footer/footer.tsx:79]: > I'm just seeing how that page was originally implemented, i.e. `footerContext`. Instead of `getSocialMediaPlatformName(url)`, add the label text to the `footerContext` directly.
> 
> ```
> footerContext = [
> ...
> {
>     socials: [
>       {
>         url: "https://twitter.com/saucedopen",
>         icon: <FaXTwitter className="text-2xl hover:text-light-slate-10  text-light-slate-9" />,
> 				label: "OpenSauced on Twitter"
>       },
> 			....
>     ],
>   },
> ```
> 
> and then in the JSX:
> 
> ```js
>           {footerContext[2].socials?.map(({ url, icon, label }, index) => (
>             <a target="_blank" aria=label={label} href={url} key={index} rel="noopener noreferrer">
>               {icon}
>             </a>
>           ))}
> ```

Oh Great! 
Thank you, @nickytonline. This is perfect 😃.

Comment (RitaDee) [reply components/organisms/Footer/footer.tsx]: Done

File: components/organisms/Footer/footer.tsx [hunk 5]
```diff
@@ -32,51 +32,38 @@ const footerContext = [
...
       },
       {
         url: "https://www.youtube.com/opensauced",
         icon: <AiFillYoutube className="text-2xl hover:text-light-slate-10  text-light-slate-9" />,
+        label: "OpenSauced on YouTube",
       },
       {
         url: "https://discord.com/invite/U2peSNf23P",
         icon: <FaDiscord className="text-2xl hover:text-light-slate-10  text-light-slate-9" />,
+        label: "OpenSauced on Discord",
```
Comment (nickytonline) [inline components/organisms/Footer/footer.tsx:55]:
```suggestion
        label: "OpenSauced Discord community",
```

**Review by nickytonline — CHANGES_REQUESTED** [review]
One small tweak and this is good to go @RitaDee! Thanks for your patience!

File: components/organisms/Footer/footer.tsx (hunk 5 above)
Comment (RitaDee) [reply components/organisms/Footer/footer.tsx]: Now fixed. Thanks again for the review.

**Review by nickytonline — APPROVED** [review]
Thanks for making the app more accessible @RitaDee! 🚀
