### PR TITLE
fix: now the outline button shows button text when disabled

### LINKED ISSUE #3484: Bug: Back button in the All Contributions tree map is not visible and doesn't work
### Describe the bug

There's an orange rectangle  in the All Contributions tree map in the Activity dashboard of Contributor Insights Page. I highlighted it and learned that it's a "Back" button.

There is no text available on the rectangle unless it's highlighted (on the desktop). Also, nothing happened when I click it.

#### Initial State

Screenshot 2024-05-27 132844

#### Highlighted

Screenshot 2024-05-27 132704

### Steps to reproduce

1. Go to a Workspace that holds Contributor Insights pages.
2. Open a page in Contributor Insights.
3. Navigate to the "Activity" tab.
4. You will see an orange rectangle in the All Contributions tree map.
5. Highlight the rectangle. You will see a "Back" text.
6. Click it. It does nothing.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now the button text appears when a button of variant `outline` is disabled.

This fixes the issue in #3484, but anywhere else in the project that has a button of variant `'outline` will benefit from this fix.

The files in `components/atoms/ToggleGroup/Button` were not used in the project and confused me initially when I added new Storybook stories. They have been removed from the project.

## Related Tickets & Documents

Fixes #3484

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-05-27 at 10 15 39

**After**

CleanShot 2024-05-27 at 10 16 04

CleanShot 2024-05-27 at 10 14 13

## Steps to QA

1. Go to a contributor insight in any workspace or create one with at least one contributor.
2. Go to the activity tab
3. Notice the contributor treemap disabled back button now has visible text.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

File: components/shared/Button/button.tsx [hunk 1]
```diff
@@ -29,26 +29,25 @@ const Button = React.forwardRef<HTMLElement, ButtonsProps>(
   ) => {
     const styles: Record<ButtonsProps["variant"], string> = {
       primary: `bg-light-orange-9 text-light-orange-2 border-light-orange-9 hover:bg-light-orange-10 ${
-        disabled ? "bg-light-orange-7 hover:bg-light-orange-7 pointer-events-none" : ""
```
Comment (nickytonline) [inline components/shared/Button/button.tsx:32]: Pointer events being set to none is not necessary since you can still interact via the keyboard. As well, it prevents the mouse cursor from changing to not allowed.

**Review by brandonroberts — APPROVED** [review]
