### PR TITLE
fix: add to list action menu needs better design when empty

### LINKED ISSUE #2232: Style: add to list action menu needs better design when empty
### Type of feature

🎨 Style

### Current behavior

The add-to-list action menu needs a better design: 
image

If you go to any profile page you might see it there. 

### Suggested solution

I would suggest to use a component like the one we have in the others action menu: 
image

## Related code: 

https://github.com/open-sauced/app/blob/8bf71afd46f9f720595ed7dfbd97cb44c726a267/components/molecules/ContributorProfileHeader/contributor-profile-header.tsx#L447-L467

The share button code for reference: 

https://github.com/open-sauced/app/blob/6c79d5e023c828cc9b726d8285ad14c999b544cc/components/ListHeader/list-header.tsx#L57-L67

### Instruction

Adding margin and padding to the code in the contributor profile header and converting the text to div would solve the issue. 

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by Anish0203**
## Description

This PR fixes the design of the add to list action menu when it is empty.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2232 

## Mobile & Desktop Screenshots/Recordings

Before:
before_action_menu

After:
after_action_menu

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

### CODE REVIEW

File: components/molecules/ContributorProfileHeader/contributor-profile-header.tsx [hunk 1]
```diff
@@ -449,7 +449,7 @@ const AddToListDropdown = ({ username }: { username: string }) => {
       open={selectListOpen}
       setOpen={setSelectListOpen}
       emptyState={
-        <div className="">
+        <div className="mt-1 mr-2 px-6 py-2">
```
Comment (a0m0rajab) [inline components/molecules/ContributorProfileHeader/contributor-profile-header.tsx:452]: Just out of curiosity, why did not we have `p-1 m-1` directly?

**Review by a0m0rajab — APPROVED** [review]

File: components/molecules/ContributorProfileHeader/contributor-profile-header.tsx (hunk 1 above)
Comment (Anish0203) [reply components/molecules/ContributorProfileHeader/contributor-profile-header.tsx]: Thanks @a0m0rajab and @nickytonline for the suggestions. I have made the changes accordingly.
