### PR TITLE
fix: updated styles of create insights links in sidebar

### LINKED ISSUE #3174: Bug: Create insight link looks like a button
Links to create new insights if you have none look like buttons even though they're links. As well the style doesn't really fit with the sidebar. I had a quick chat with @isabensusan about changing these styles to links instead when I got back from vacation.

CleanShot 2024-04-11 at 19 57 11

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Updates create new insight CTA link styles.

## Related Tickets & Documents

Fixes #3174

## Mobile & Desktop Screenshots/Recordings

**Before**

image

**After**

CleanShot 2024-04-11 at 19 59 34

## Steps to QA

1. Ensure you're logged in.
2. Create a new workspace or go to a workspace without repository or contributor insights.
3. Notice the Create links look like links now.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

File: components/shared/AppSidebar/InsightsPanel.tsx [hunk 1]
```diff
@@ -73,16 +72,16 @@ export const InsightsPanel = ({ title, insights, type, isLoading, workspaceId }:
               })
             ) : (
               <li className="py-1 px-3 text-sm flex flex-col w-full justify-between gap-2">
-                <p>You don&apos;t have any Insights yet!</p>
-                <Button
+                <p>You don&apos;t have any Insights yet</p>
```
Comment (nickytonline) [inline components/shared/AppSidebar/InsightsPanel.tsx:75]: I removed the exclamation point as it seemed too urgent.

**Review by isabensusan — APPROVED** [review]
LGTM!

**Review by jpmcb — APPROVED** [review]
🥇
