### PR TITLE
fix: now destructive variant is used for destructive actions in the app

### LINKED ISSUE #2353: Bug: Destructive CTAs have colour contrast issues
Destructive CTAs have colour contrast issues

CleanShot 2023-12-15 at 14 55 18

CleanShot 2023-12-15 at 14 57 04

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now destructive actions in the application use the destructive button variant which fixes colour contrast issues in the app for the current destructive CTA button stylings.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2353

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2023-12-15 at 16 27 33

CleanShot 2023-12-15 at 16 28 01

CleanShot 2023-12-15 at 16 28 22

**After**

CleanShot 2023-12-15 at 16 29 19

CleanShot 2023-12-15 at 16 29 48

CleanShot 2023-12-15 at 16 30 02

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

File: components/atoms/Button/button.tsx [hunk 1]
```diff
@@ -71,7 +72,12 @@ const Button = React.forwardRef<HTMLElement, ButtonsProps>(
     }
 
     return (
-      <button className={rootClass} ref={ref as ForwardedRef<HTMLButtonElement>} {...props}>
+      <button
+        className={rootClass}
+        ref={ref as ForwardedRef<HTMLButtonElement>}
+        onClick={!disabled ? onClick : undefined}
```
Comment (nickytonline) [inline components/atoms/Button/button.tsx:78]: If the button is disabled, the `onClick` is not registered.

File: components/organisms/InsightPage/DeleteInsightPageModal.tsx [hunk 2]
```diff
@@ -65,16 +64,7 @@ const DeleteInsightPageModal: FC<ModalProps> = ({
...
-            loading={isLoading}
-            disabled={disabled}
-            onClick={handleOnConfirm}
-            variant="default"
-            className={clsx(
-              "bg-light-red-6 border border-light-red-8 hover:bg-light-red-7 text-light-red-10",
-              disabled && "cursor-not-allowed !bg-light-red-4 hover:!none !border-light-red-5 !text-light-red-8"
-            )}
-          >
+          <Button loading={isLoading} disabled={disabled} onClick={handleOnConfirm} variant="destructive">
```
Comment (nickytonline) [inline components/organisms/InsightPage/DeleteInsightPageModal.tsx:67]: The button and other delete buttons below are now using the `destructive` variant.

**Review by OgDev-01 — APPROVED** [review]
🍕

**Review by brandonroberts — APPROVED** [review]
