### PR TITLE
fix: ToggleSwitch component has required label via aria-label or aria-labelledby

### LINKED ISSUE #2036: Require ToggleSwitch component to have a label
Currently the toggle switch does not have a label. Have it require an `aria-label` or `aria-labelledby` attribute.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now the `<ToggleSwitch />` component requires a label via either the `ariaLabel` prop or the `ariaLabellebBy` prop.

See the MDN docs on the [aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label) and [aria-labelledby](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-labelledby) attributes.

I came across this fix while working on #1977

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2036
Relates to #1977

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/833231/8d947222-902e-41f8-b678-d1d132230ca5

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/atoms/ToggleSwitch/toggle-switch.tsx [hunk 1]
```diff
@@ -1,27 +1,33 @@
 import * as Switch from "@radix-ui/react-switch";
 import clsx from "clsx";
 
-interface ToggleSwitchProps {
+type ToggleSwitchProps = {
```
Comment (nickytonline) [inline components/atoms/ToggleSwitch/toggle-switch.tsx:4]: The props look a little more complex, but basically it's so that you can either have `ariaLabel` or `ariaLabelledBy`, not both.

**Review by OgDev-01 — APPROVED** [review]
LGTM

**Review by brandonroberts — APPROVED** [review]
