### PR TITLE
fix: fixed star search URL for SEO

### LINKED ISSUE #3219: Bug: Add a hyphen in the StarSearch URL
Update the StarSearch URL so that it has a hyphen in it.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Updates the StarSearch url from `/starsearch` to `/star-search`

## Related Tickets & Documents

Fixes #3219

## Steps to QA

1. Ensure you're in the feature flag cohort for Star Search.
2. Navigate to `/star-search` and the StarSearch page loads.
3. Navigate to `/starsearch` and the p. age 404s.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Review by bdougie — APPROVED** [review]
🚀🚀🚀

File: components/organisms/TopNav/top-nav.tsx [hunk 1]
```diff
@@ -89,9 +89,9 @@ const Nav = ({ className }: { className?: string }) => {
...
             <Link
               className={`tracking-tight font-medium text-sm text-slate-700 hover:text-orange-500 flex gap-2 items-center transition-all ${getActiveStyle(
-                router.pathname === "/starsearch"
+                router.pathname === "/star-search"
               )}`}
-              href={"/starsearch"}
+              href={"/star-search"}
             >
               <img src="/assets/star-search-logo.svg" alt="Star Search logo" className="w-5 h-5" />
               <p className="mt-0.5">StarSearch</p>
```
Comment (zeucapua) [inline components/organisms/TopNav/top-nav.tsx:97]: Would we need to change the title and chat name and add the hyphen?

**Review by zeucapua — APPROVED** [review]

**Review by brandonroberts — APPROVED** [review]
