### PR TITLE
fix: now legend labels in most active graph tooltip render properly

### LINKED ISSUE #1928: Bug: Legend Labels in Most Active Graph Tooltip Render Incorrectly
### Describe the bug

Legend Labels in Most Active Graph Tooltip Render Incorrectly

### Steps to reproduce

1. Navigate to http://localhost:3000/lists/fbaf2278-69e9-4a2f-9ccc-8dc67af5177e/activity
2. Hover over a bar in the graph.
3. Notice the legend labels are incorrect.

CleanShot 2023-10-17 at 11 26 00

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Fixed label keys appearing in the most active contributors graph bar tooltips.

You can see the fix at https://deploy-preview-1927--oss-insights.netlify.app/lists/fbaf2278-69e9-4a2f-9ccc-8dc67af5177e/activity

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1928

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2023-10-17 at 11 26 00

**After**

CleanShot 2023-10-17 at 14 32 49

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by OgDev-01 — APPROVED** [review]

File: components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx [hunk 1]
```diff
@@ -221,15 +219,14 @@ function RowTooltip({
...
-              <div key={key} className={clsx("flex items-center gap-2 font-bold", { "font-bold": true })}>
-                <div
-                  className="w-3 h-3 rounded-sm"
-                  style={{ backgroundColor: labels.includes(key) ? value.color : "gray" }}
-                ></div>
-                <div className={clsx(key === highlightedStat ? "font-bold" : "font-light")}>{value.title}</div>
-              </div>
-            ))}
+            {Object.entries(dataLabelsList)
+              .filter(([key]) => labels.includes(key))
```
Comment (nickytonline) [inline components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx:223]: only show labels in the legend for data we have atm.

File: components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx [hunk 2]
```diff
@@ -204,12 +204,10 @@ export default function MostActiveContributorsCard({
 
 function RowTooltip({
   contributor,
-  highlightedStat,
   dataLabels,
   children,
 }: {
   contributor: ContributorStat;
-  highlightedStat: StatKeys;
```
Comment (nickytonline) [inline components/molecules/MostActiveContributorsCard/most-active-contributors-card.tsx:212]: There didn't seem to be a reason for this aside from bolding the first item in the legend.

**Review by jpmcb — APPROVED** [review]
