### PR TITLE
fix: validate user exists for `/user/<username>/card` page

### LINKED ISSUE #3930: Bug: dev card page loads non-existent user
If the username for the dev card page does not exist, we should 404 the page instead of displaying a non-existent user dev card page.

CleanShot 2024-08-12 at 18 38 17

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Implements a server side check that validates a user with the username in the URL exists, otherwise throws a 404 not found.

## Related Tickets & Documents

Closes #3930 

## Steps to QA

1. Go to a DevCard page for a non-existent user (eg `/user/zeucapua2/card`)
2. Ensure you are given a 404 page.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

## [optional] What gif best describes this PR or how it makes you feel?

john-cena-no-gif-by-buzzfeed

### CODE REVIEW

File: pages/u/[username]/card.tsx [hunk 1]
```diff
@@ -55,6 +58,17 @@ export async function getServerSideProps(context: GetServerSidePropsContext) {
     };
   }
 
+  const { data: userData, error } = await fetchApiData({
+    path: `users/${username}`,
+    pathValidator: () => safeParse(GitHubUserNameSchema, username).success,
+  });
+
+  if (error || !userData) {
```
Comment (nickytonline) [inline pages/u/[username]/card.tsx:66]: If it's an error that is not a 404, we should log the error via Sentry and let the 500 page load up.

**Review by nickytonline — CHANGES_REQUESTED** [review]

**Review by brandonroberts — APPROVED** [review]

**Review by nickytonline — APPROVED** [review]
🚢
