### PR TITLE
fix: eslint issue by using `eslint-disable`

### LINKED ISSUE #1972: Repo: add eslint rules for console.log and unused code
### Type of feature

📦 Chore

### Current behavior

In order to minimize nitpick items such as leftover console.log and commented out code, this adds those rules to the eslint config, so the build fails with an error. 

Our lint rules are here 

https://github.com/open-sauced/app/blob/beta/.eslintrc.json

It might involve cleanup of existing occurrences

### Suggested solution

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by brainconnect93**
## Description
In this PR I worked on the eslint console.log issue and I rectified the issue by using the `eslint-disable` on all occurrences.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1972

## Mobile & Desktop Screenshots/Recordings

Before 👇 

cons

After 👇 

after-task2

## Added tests?

- [ ] 👍 yes
- [X] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

### CODE REVIEW

**Comment by brandonroberts** [comment]
Thanks @brainconnect93. We don't want to completely disable `eslint` for each file. For example, in the file where the console log is would have an `// eslint disable no-console` above it.

File: components/ListHeader/list-header.tsx [hunk 1]
```diff
@@ -1,3 +1,5 @@
+/* eslint-disable */
```
Comment (nickytonline) [inline components/ListHeader/list-header.tsx:1]: refactor (blocking): eslint-disable should not be use to disable all linting for files where console statements are used. Use `eslint-disable-next-line` instead. e.g.

```javascript
try {
  await navigator.clipboard.writeText(url);
  toast({ description: "Copied to clipboard", variant: "success" });
} catch (error) {
	// eslint-disable-next-line no-console
  console.log(error);
}
```

**Review by nickytonline — CHANGES_REQUESTED** [review]

File: components/ListHeader/list-header.tsx (hunk 1 above)
Comment (brainconnect93) [reply components/ListHeader/list-header.tsx]: @nickytonline please kindly check the `code standard` linters that are failing, I have worked on all the files where we have the console statement and I don't know why the code standard is still failing. Kindly let me know if there is anything am missing.
Thank you.

**Review by nickytonline — CHANGES_REQUESTED** [review]
Thanks for making the changes @brainconnect93. It looks like there are still some `/* eslint-disable */` comments still. Once those are removed, this should be good to merge.

CleanShot 2023-10-25 at 07 43 03

Thanks for working on this!

File: components/molecules/InsightPageCard/insight-page-card.tsx [hunk 2]
```diff
@@ -54,6 +54,17 @@ const InsightPageCard = ({ insight, user }: InsightPageCardProps): JSX.Element =
...
+  const handleCopyToClipboard = async (content: any) => {
+    const url = new URL(content, window.location.origin).toString();
+    try {
+      await navigator.clipboard.writeText(url);
+    } catch (error) {
+      // eslint-disable-next-line no-console
+      console.log(error);
+    }
+  };
+
```
Comment (nickytonline) [inline components/molecules/InsightPageCard/insight-page-card.tsx:67]: I believe this is work that @OgDev-01 was doing. The `handleCopyToClipboard` shouldn't be a part of this PR.

**Review by nickytonline — CHANGES_REQUESTED** [review]
This looks good @brainconnect93 aside from some code that I believe is a part of another PR.

Thanks for your patience on this!

File: components/molecules/InsightPageCard/insight-page-card.tsx (hunk 2 above)
Comment (brainconnect93) [reply components/molecules/InsightPageCard/insight-page-card.tsx:67]: @nickytonline so what do you suggest I do with the situation on ground

Comment (nickytonline) [reply components/molecules/InsightPageCard/insight-page-card.tsx:67]: In your branch from the command line, you can run `git checkout upstream/beta -- components/molecules/InsightPageCard/insight-page-card.tsx` or if it says it can't find `upstream` run `git checkout beta -- components/molecules/InsightPageCard/insight-page-card.tsx`.

This will put that file back to what it is on the beta branch.

Comment (brainconnect93) [reply components/molecules/InsightPageCard/insight-page-card.tsx:65]: @nickytonline, I ran the line of code in my terminal and I solved the issue by inputting `// eslint-disable-next-line no-console` on line 61 of the `insight-page-car.tsx` file but am still getting a failing code standard. What could be the problem with the project and what am i doing wrongly that is making the eslint fail code standard

Comment (nickytonline) [reply components/molecules/InsightPageCard/insight-page-card.tsx]: I've fixed this file by reverting it back to what it is in the `beta` branch. The change is in d2e73a9c29d06c949cc5a81ca82b6d29fbf755cd.

The only file to add the eslint rule is `./lib/utils/copy-to-clipboard.ts`.

After that this should be good.

Comment (nickytonline) [reply components/molecules/InsightPageCard/insight-page-card.tsx]: Grab the latest of your branch by running `git pull` when you have a chance and make the suggested change above. Thanks for your patience @brainconnect93!

**Comment by nickytonline** [comment]
Just two left @brainconnect93. I think they're new files from the merge of latest in your branch.

```
./lib/hooks/fetchGithubOrgTeams.ts
33:5  Error: Unexpected console statement.  no-console

./lib/hooks/fetchGithubTeamMembers.ts
34:5  Error: Unexpected console statement.  no-console
```

**Review by nickytonline — APPROVED** [review]
Thanks for this @brainconnect93! :shipit:

**Review by OgDev-01 — APPROVED** [review]

**Comment by brainconnect93** [comment]
Thanks, @nickytonline, @OgDev-01 it's a great pleasure working on the PR and I look forward to collaborating and working on more PRs
