### PR TITLE
fix: now repo page OG images are corrext for production

### LINKED ISSUE #3180: Bug: Repository OG image in production has a base URL of http://localhost:3000
For some reason `const { NEXT_PUBLIC_BASE_URL = "http://localhost:3000" } = process.env;` resolves to `http://localhost:3000` causing the OG images for repository pages to be broken.

I cam across this while writing a blog post about how we generate OG images.

e.g. visit https://app.opensauced.pizza/s/open-sauced/app and you'll see the following if you open the browser dev tools.

CleanShot 2024-04-12 at 23 29 28

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now, localhost is only used if `NEXT_PUBLIC_BASE_URL` isn't set for the repository page repo image.

## Related Tickets & Documents

Fixes #3180
Relates to #3117

## Steps to QA

1. Go to any repository page, e.g. https://deploy-preview-3179--oss-insights.netlify.app/s/open-sauced/app
2. Open the dev tools and expand the `<head>` section.
3. Notice the og:image and twitter:image have base URLs that are the deployment preview.

CleanShot 2024-04-12 at 23 22 49

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

File: pages/s/[org]/[repo]/index.tsx [hunk 1]
```diff
@@ -29,8 +29,10 @@ export async function getServerSideProps(context: GetServerSidePropsContext) {
   const { owner } = await response.json();
 
   const range = (context.query.range ? Number(context.query.range) : 30) as Range;
-  const { NEXT_PUBLIC_BASE_URL = "http://localhost:3000" } = process.env;
-  const { href: ogImageUrl } = new URL(getRepositoryOgImage(repoData, range), NEXT_PUBLIC_BASE_URL);
+  const { href: ogImageUrl } = new URL(
+    getRepositoryOgImage(repoData, range),
+    process.env.NEXT_PUBLIC_BASE_URL || "http://localhost:3000"
```
Comment (nickytonline) [inline pages/s/[org]/[repo]/index.tsx:34]: I swtiched the code to what we do for the workspace OG image, but I'm confused why my original code `const { NEXT_PUBLIC_BASE_URL = "http://localhost:3000" } = process.env;` didn't work. They seem equivalent. 🙃

**Review by jpmcb — APPROVED** [review]
🚢
