### PR TITLE
fix: dropdown flickery on single highlight card

### LINKED ISSUE #2039: Bug: Menu for a highlight won't open so can't edit highlight
### Describe the bug

Go to one of your highlights. Try clicking on the three dots menu beside the X/Twitter button. The menu opens and closes very quickly.

### Steps to reproduce

Here's the issue in action when I try to edit one of my own highlights.

CleanShot 2023-11-02 at 08 57 24

This looks similar to the date picker issue we had in Safari @OgDev-01, but this one is happening in Chromium based browsers.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR fixes the single highlight card issue with the edit dropdown

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
fixes #2039 
fixes https://github.com/open-sauced/app/issues/1896

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/62995161/699cb4da-7014-4b5f-80c4-6275c68c1091

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/molecules/ContributorHighlight/contributor-highlight-card.tsx [hunk 1]
```diff
@@ -175,6 +176,12 @@ const ContributorHighlightCard = ({
     }
   };
 
+  const handleClickOutsideDropdownContent = (e: MouseEvent) => {
```
Comment (nickytonline) [inline components/molecules/ContributorHighlight/contributor-highlight-card.tsx:179]: Have we used this logic elsewhere yet @OgDev-01. I feel like I've seen this code before. Just mentioning it as it might make sense to promote this to a custom hook which could be done in a separate PR.

Comment (OgDev-01) [reply components/molecules/ContributorHighlight/contributor-highlight-card.tsx:179]: Yes i have, I can quickly add that to this PR... Thanks for mentioning 👍

File: components/molecules/ContributorHighlight/contributor-highlight-card.tsx [hunk 2]
```diff
@@ -122,10 +122,11 @@ const ContributorHighlightCard = ({
   const [host, setHost] = useState("");
   const [dropdownOpen, setDropdownOpen] = useState(false);
   const { follow, unFollow, isError } = useFollowUser(
-    dropdownOpen && loggedInUser && loggedInUser?.user_metadata.user_name !== user ? user : ""
+    dropdownOpen && loggedInUser && loggedInUser.user_metadata.user_name !== user ? user : ""
```
Comment (nickytonline) [inline components/molecules/ContributorHighlight/contributor-highlight-card.tsx:125]: nit: should be OK because if the user is not logged in, `undefined` will still not equal `user`.

```suggestion
    dropdownOpen && loggedInUser?.user_metadata.user_name !== user ? user : ""
```

**Review by brandonroberts — APPROVED** [review]
