### PR TITLE
fix: allow repos and contributors to be added to workspaces from explore page

### LINKED ISSUE #3671: Bug: Contributor Insights are still called lists on the Repository Insight page
### Describe the bug

Screenshot 2024-07-02 at 5 15 13 PM

### Steps to reproduce

1. Create a repository insight
2. View the contributors tab
3. Note the "Add to list" button

### PR DESCRIPTION
**Pull request by brandonroberts**
## Description

- Fixes flow where repositories can be added to a new workspace from the explore page
- Fixes flow where contributors can be added to a contributor insight from the explore page
- Fixes copy for adding contributor insights from explore page

## Related Tickets & Documents

Closes #3671 
Closes https://github.com/open-sauced/app/issues/2857
## Mobile & Desktop Screenshots/Recordings

image

image

## Steps to QA

1. Go to the explore page
2. Login
3. Choose some repositories from the dashboard, click Add to Workspace
4. Follow flow to create a new workspace with the selected repositories

---
Contributor flow
1. Choose the contributors tab
2. Choose some contributors, click Add to Insight
3. Follow flow to add Contributors to new/existing Insight

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

File: components/organisms/Repositories/repositories.tsx [hunk 1]
```diff
@@ -146,7 +151,7 @@ export default function Repositories({ repositories, showSearch = true }: Reposi
             <div className="flex justify-between p-3 px-6 items-center border-b-2 text-light-slate-11">
               <div>{selectedRepos.length} Repositories selected</div>
               <Button onClick={handleOnAddtoInsights} variant="primary">
-                Add to Insight Page
+                {workspaceId ? "Add to Insight Page" : "Add to Workspace"}
               </Button>
             </div>
```
Comment (nickytonline) [inline components/organisms/Repositories/repositories.tsx:156]: Since this is being updated for workspaces, might as well make it more accessible as well.

```suggestion
          <div
            aria-hidden={selectedRepos.length === 0}
            className={clsx(
              selectedRepos.length > 0 ? "flex" : "hidden",
              `justify-between p-3 px-6 items-center border-b-2 text-light-slate-11`
            )}
          >
            <div>{selectedRepos.length} Repositories selected</div>
            <Button onClick={handleOnAddtoInsights} variant="primary">
              {workspaceId ? "Add to Insight Page" : "Add to Workspace"}
            </Button>
          </div>
```

**Review by nickytonline — APPROVED** [review]
🚢

**Review by bdougie — APPROVED** [review]
🚀
