### PR TITLE
fix: Fix re-rendering of Highlights "Repositories" table with duplicates

### LINKED ISSUE #1779: Bug: Highlights "Repositories" table rerenders with duplicates and spills over page eventually
### Describe the bug

Noticed this while investigating: https://github.com/open-sauced/app/issues/1778

https://github.com/open-sauced/app/assets/23109390/8c486770-0c8e-4fe2-9034-fde0bada0b48

Watch the right side as I quickly flip between the "Home" and "Following" tabs: the "Repositories" field grows and grows, eventually spilling over the bottom of the page and containing many of the same repo, over and over again.

A few suggestions:
- Duplicate repos do not make sense
- We should have some sane limit, maybe 15 at most? Open to suggestions
- This table should not spill over the bottom of the page
- Rerendering this each time the user flips from the "Home" tab to the "Following" tab (and back again) probably also doesn't make sense. A static rendered table of repositories would be the most smooth user experience.

### Steps to reproduce

1. Go to https://insights.opensauced.pizza/feed
2. Flip many times from "Home" to "Following" (and back again)
3. Notice the "Repositories" table on the right is rerendered many times and eventually spills over the page containing duplicates.

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by 5hraddha**
## Description
This PR:
1. fixes the React paint issue by keeping the key props value unique and thus, also handles the vertical expansion of "Repositories" table that was leading to spillage.
2. filters the duplicate repos to  make sure only unique repos are rendered in Highlights "Repositories" table at `/feed`.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Fixes #1779

## Mobile & Desktop Screenshots/Recordings
**Before the change**

https://github.com/open-sauced/app/assets/27571141/d8044fd5-f1ee-4390-a1e2-8a700b756a43

**After the change**

https://github.com/open-sauced/app/assets/27571141/820cbc74-45ee-456b-889a-132a5dfe1413

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/molecules/HighlightsFeedCard/highlights-filter-card.tsx [hunk 1]
```diff
@@ -21,7 +21,7 @@ const HighlightsFilterCard = ({ repos, setSelected, selectedFilter }: Highlights
         {repos.map(({ repoName, repoIcon, full_name }) => (
           <div
             onClick={() => handleClick(full_name)}
-            key={(repoName + repoIcon) as string}
+            key={(full_name + repoIcon) as string}
```
Comment (nickytonline) [inline components/molecules/HighlightsFeedCard/highlights-filter-card.tsx:24]: The `full_name` is enough for the key.

**Review by OgDev-01 — APPROVED** [review]
Thanks for this fix @5hraddha 👏👏

**Review by brandonroberts — APPROVED** [review]
🍕
