### PR TITLE
fix: now top navigation is no longer squished or resized vertically

### LINKED ISSUE #2740: Bug: Top navigation squished on mobile
Currently the top navigation gets squished on mobile.

@isabensusan suggest adding some of those links to the sidebar for mobile only.

https://files.slack.com/files-pri/T033MQB5Q0K-F06L7PPBKNY/image.png

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now, top navigation is no longer squished or resized vertically. The Explor and Highlights links in the top navigation move to the sidebar once the medium breakpoint and smaller is hit.

**Waiting for #2758 to be merged first.**

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2740

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-02-25 at 12 25 25

**After**

CleanShot 2024-02-25 at 12 23 45

## Steps to QA

1. Ensure you're logged in
2. Go to any workspace
3. Resize the window
4. As the screen gets smaller some of the top navigation links will move to the sidebar
5. Notice the top navigation does not resize vertically.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]

File: components/atoms/Tooltip/tooltip.tsx [hunk 1]
```diff
@@ -9,12 +9,13 @@ interface TooltipProps {
...
   tipClassName?: string;
+  defaultOpen?: boolean;
 }
-const Tooltip = ({ children, content, className, direction }: TooltipProps): JSX.Element => {
+const Tooltip = ({ children, content, className, direction, defaultOpen }: TooltipProps): JSX.Element => {
   const { Portal, Root, Content, Trigger, Arrow } = TooltipPrimitive;
 
   return (
-    <Root delayDuration={300}>
+    <Root delayDuration={300} defaultOpen={defaultOpen}>
```
Comment (nickytonline) [inline components/atoms/Tooltip/tooltip.tsx:18]: `defaultOpen` starts with the tooltip open. We generally don't do that, but in the case of onboarding, there was a bespoke implementation of a tooltip with it always open. This  allows us to replace that bespoke tooltip. And when you click, it disappears and then functions like a tooltip normally does.

File: components/organisms/TopNav/top-nav.tsx [hunk 2]
```diff
@@ -8,43 +8,33 @@ import useSession from "lib/hooks/useSession";
...
-            </div>
-          </div>
-        )}
-      </div>
     </header>
   );
 };
 
-const Nav = ({ className, name = "Main" }: { className?: string; name?: string }) => {
+const Nav = ({ className }: { className?: string }) => {
```
Comment (nickytonline) [inline components/organisms/TopNav/top-nav.tsx:36]: No name is passed in now, because we only have one `Nav` for all screen sizes.
