### PR TITLE
fix: top navigation workspace link works as expected now

### LINKED ISSUE #2723: Feature: Redirect to workspaces dashboard when visiting /workspaces
### Type of feature

🍕 Feature

### Current behavior

With our current routing structure, if you navigate to `/workspaces`, it takes you to the explore page with `workspaces` as the topic.

Instead, this should take you to your selected/default workspace

### Suggested solution

_No response_

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### LINKED ISSUE #2792: Bug: `/feed` redirect breaks "Workspace" and other headers when logging in
### Describe the bug

When logging into prod, the top header is broken:

sad-redirect

This is fixed by removing the `?redirectedFrom=%2F` query param. You can see I do that in this second gif. This seems to fix the issue.

_But_, if you log out and log back in again, go to the feed, it returns to that same behavior.

### Steps to reproduce

1. Log out
2. Log in
3. Go to the feed / "Highlights"
4. Attempt to go to workspaces by clicking the top nav "Workspaces" header - unsuccessful: note the `?redirectedFrom=%2F` in the query

### Browsers

Confirmed this behavior on Firefox and Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

~This was not reproducible in a local development and environment. Now, if `redirectFrom` is in the querystring, it redirects to it.~

We're no longer redirecting from `/` for the Workspaces link in the top navigation. I've created `/workspaces` that now redirects to your last accessed workspace.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2792
Fixes #2723

## Steps to QA

1. Log out
2. Log in
3. Go to the feed / "Highlights"
4. Click on the Workspace link in the top navigation.
5. You're redirected to the last workspace accessed or your personal workspace if none was accessed before.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

The

### CODE REVIEW

File: components/molecules/AuthSection/auth-section.tsx [hunk 1]
```diff
@@ -43,12 +43,6 @@ const AuthSection: React.FC = ({}) => {
     }
   }, []);
 
-  useEffect(() => {
```
Comment (nickytonline) [inline components/molecules/AuthSection/auth-section.tsx:46]: This is handled in the middleware now.

File: middleware.ts [hunk 2]
```diff
@@ -54,7 +54,10 @@ const loadSession = async (request: NextRequest, sessionToken?: string) => {
 export async function middleware(req: NextRequest) {
   const res = NextResponse.next();
 
-  if (!pathsToMatch.some((matcher) => pathToRegexp(matcher).test(req.nextUrl.pathname))) {
+  if (
```
Comment (nickytonline) [inline middleware.ts:57]: There's still the Next.js middleware issue mentioned in the comment in middleware code, https://github.com/open-sauced/insights/pull/1549, so just adding another check here so that `redirectFrom` is handled by middleware if you're logged in.

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
🤔 Code change looks fine, but I get into a loop with a certain workflow

1. Open the deploy preview
2. Get redirected to the feed with `redirectedFrom=%2F` as a query param
3. Click Connect to GitHub
4. Redirect back
5. Click on Workspace
6. Page gets stuck in a loop

**Comment by nickytonline** [comment]
> 🤔 Code change looks fine, but I get into a loop with a certain workflow
> 
> 
> 
> 1. Open the deploy preview
> 
> 2. Get redirected to the feed with `redirectedFrom=%2F` as a query param
> 
> 3. Click Connect to GitHub
> 
> 4. Redirect back
> 
> 5. Click on Workspace
> 
> 6. Page gets stuck in a loop
> 
> 
> 
> 

Let me look into that. I'll put it into draft until I figure out that loop.

**Comment by nickytonline** [comment]
> 🤔 Code change looks fine, but I get into a loop with a certain workflow
> 
> 1. Open the deploy preview
> 2. Get redirected to the feed with `redirectedFrom=%2F` as a query param
> 3. Click Connect to GitHub
> 4. Redirect back
> 5. Click on Workspace
> 6. Page gets stuck in a loop

I can reproduce it. For some reason like the original issue, I can't replicate it on localhost. 😅

**Comment by nickytonline** [comment]
Take this for a spin again @brandonroberts as the link is different now.

File: middleware.ts [hunk 3]
```diff
@@ -65,6 +65,13 @@ export async function middleware(req: NextRequest) {
     data: { session },
   } = await supabase.auth.getSession();
 
+  if (session?.user && req.nextUrl.pathname === "/workspaces") {
```
Comment (nickytonline) [inline middleware.ts:68]: There are several conditions in the middleware, four to be exact that start with `if (session?.user &&`. Not for this PR, but it'd make sense to consolidate so it's one branch for that condition and handle the subconditions within it.

**Review by brandonroberts — APPROVED** [review]
Works consistently for me now across navigations 👍

**Review by jpmcb — APPROVED** [review]
👏🏼 👏🏼 👏🏼
