### PR TITLE
fix: now page limit dropdown filters works on repo table

### LINKED ISSUE #2209: Bug: Show more contributors isn't working
### Describe the bug

When I'm on an insight page, and I want to expand the number of contributors that are shown, nothing happens.

https://github.com/open-sauced/app/assets/34313413/ae18df56-7a48-4ccb-b506-7a7f64334a0f

### Steps to reproduce

- Go to: https://app.opensauced.pizza/pages/BekahHW/1035/contributors?range=30&limit=50
- Only ten displays

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### LINKED ISSUE #2290: Bug: filter not showing the correct number on explore page.
### Describe the bug

You can see from the image below, it should be showing 10/page, but if you look next to repositories, it shows you that it's displaying 50. 

image

### Steps to reproduce

Go to the explore page. 

You can check it out [here](https://app.opensauced.pizza/ai/dashboard/filter/most-active?range=30)

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR fixes the issue with page limit update on the filters dashboard table

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
fixes #2209
fixes #2290

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/62995161/da0927a2-0013-4b9f-8d10-5f476af580bc

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/organisms/Repositories/repositories.tsx [hunk 1]
```diff
@@ -37,7 +37,7 @@ const Repositories = ({ repositories }: RepositoriesProps): JSX.Element => {
     isError: repoListIsError,
     isLoading: repoListIsLoading,
     setPage,
-  } = useRepositories(repositories, Number(range), Number(limit));
+  } = useRepositories(repositories, Number(range ?? 30), Number(limit ?? 10));
```
Comment (nickytonline) [inline components/organisms/Repositories/repositories.tsx:40]: refactor (blocking): set the defaults where the variables are destructure on line 28

```diff
- const { pageId, toolName, selectedFilter, userOrg, range, limit } = router.query;
+ const { pageId, toolName, selectedFilter, userOrg, range = 30, limit = 10 } = router.query;
```

```suggestion
  } = useRepositories(repositories, Number(range), Number(limit));
```

File: components/organisms/Repositories/repositories.tsx [hunk 2]
```diff
@@ -130,7 +130,7 @@ const Repositories = ({ repositories }: RepositoriesProps): JSX.Element => {
               <TableTitle>Contributors</TableTitle>
             </div>
             <div className={clsx(classNames.cols.last30days, "hidden xl:flex")}>
-              <TableTitle>Last 30 Days</TableTitle>
+              <TableTitle>Last {range ?? 30} Days</TableTitle>
```
Comment (nickytonline) [inline components/organisms/Repositories/repositories.tsx:133]: refactor (blocking): use the range with the default value as mentioned up top.

```suggestion
              <TableTitle>Last {range} Days</TableTitle>
```

**Review by nickytonline — CHANGES_REQUESTED** [review]
Just a couple change requests @OgDev-01.

**Review by nickytonline — COMMENTED** [review]
The fix works, but the initial page load if there is a range in the URL causes a hydration error.

CleanShot 2023-12-06 at 16 52 27

**Comment by nickytonline** [comment]
Looks like the deploy preview is failing. 

```
7:38:29 AM: ./components/organisms/Contributors/contributors.tsx:13:23
7:38:29 AM: Type error: ""components/atoms/Select/limit-select"" has no exported member named "limitSelectMap". Did you mean "LimitSelectMap"?
7:38:29 AM:   11 | 
7:38:29 AM:   12 | import SkeletonWrapper from "components/atoms/SkeletonLoader/skeleton-wrapper";
7:38:29 AM: > 13 | import LimitSelect, { limitSelectMap } from "components/atoms/Select/limit-select";
7:38:29 AM:      |                       ^
7:38:29 AM:   14 | 
7:38:29 AM:   15 | import useContributors from "lib/hooks/api/useContributors";
7:38:29 AM:   16 | import { getAvatarByUsername } from "lib/utils/github";
```

It's now `LimitSelectMap`

https://github.com/open-sauced/app/blob/534c4646100ca37b270182e41ce7744ce19704f0/components/atoms/Select/limit-select.tsx#L15

**Comment by OgDev-01** [comment]
> The fix works, but the initial page load if there is a range in the URL causes a hydration error.

I'm still trying to figure out what element is causing the hydration that needs to be paused until client is loaded... any idea on the best way to tracking the cause of hydration?

**Comment by OgDev-01** [comment]
Hydration issue has been fixed cc: @nickytonline

**Review by nickytonline — COMMENTED** [review]
@OgDev-01, I undid all the `<ClientOnly>`s you added and added it to just the hub-page.tsx.

The issue there was the insights header being a skeleton loaded on the server side.

```jsx
          <Header>
            <ClientOnly>
              {insight ? (
                <InsightHeader insight={insight} repositories={repositories} insightId={insightId} isOwner={isOwner} />
              ) : isLoading ? (
                <div className="flex justify-between w-full h-46">
                  <div className="flex items-center gap-3">
                    <SkeletonWrapper radius={10} width={140} height={140} />
                    <div className="flex flex-col gap-3">
                      <SkeletonWrapper width={110} height={25} />
                      <SkeletonWrapper width={200} height={25} />
                      <SkeletonWrapper classNames="mt-3" width={150} height={30} />
                    </div>
                  </div>
                  <div>
                    <SkeletonWrapper classNames="mt-6" width={150} height={40} />
                  </div>
                </div>
              ) : (
                <div>Error occurred</div>
              )}
            </ClientOnly>
          </Header>
```

There's an issue still with the list page, i.e. http://localhost:3000/lists/some-list-id/contributors, because I removed all the `<ClientOnly>`s you added, but I think there is probably a small dynamic section in there somewhere. This was working before without hydration errors so not sure what caused it to start giving hydration errors.

File: layouts/lists.tsx [hunk 3]
```diff
@@ -36,15 +37,17 @@ const ListPageLayout = ({
...
+              {list && (
+                <ListHeader
+                  name={list.name}
+                  numberOfContributors={numberOfContributors}
+                  isPublic={list.is_public}
+                  listId={list.id}
+                  isOwner={isOwner}
+                />
+              )}
+            </ClientOnly>
```
Comment (nickytonline) [inline layouts/lists.tsx:50]: refactor (blocking): This needs to load server side. All the data is available in `getServerSideProps`. I removed `<ClientOnly />` and it works fine with no hydration errors.

```suggestion
            {list && (
              <ListHeader
                name={list.name}
                numberOfContributors={numberOfContributors}
                isPublic={list.is_public}
                listId={list.id}
                isOwner={isOwner}
              />
            )}
```

**Review by nickytonline — CHANGES_REQUESTED** [review]
This is working well @OgDev-01. One last change request.

File: layouts/lists.tsx (hunk 3 above)
Comment (OgDev-01) [reply layouts/lists.tsx:50]: It fails in this case as the `numberOfContributors` prop is gotten clientside. 
image

unless we want to fetch the contributors data in the server, this will keep throwing hydration errors

Comment (nickytonline) [reply layouts/lists.tsx:50]: We want to render as much markup server side for the list header. The only part of it that is coming from the client-side is the `numberOfContributors` prop, so we can just do this instead for this line in the list header component.

https://github.com/open-sauced/app/blob/e281e143feb776765e5a2fb57199366c0d9720a4/components/ListHeader/list-header.tsx#L53

```diff
          <div className="flex items-center gap-2 mt-4" id="contributorCount">
-            {numberOfContributors} Contributors
+            <ClientOnly>{numberOfContributors} Contributors</ClientOnly>
          </div>
```

**Review by nickytonline — CHANGES_REQUESTED** [review]

**Comment by nickytonline** [comment]
@OgDev-01, you'll need to merge the lates from beta to grab @jpmcb's changes for insights. Currently I'm getting this error whe I pull down your latest code.

CleanShot 2023-12-21 at 09 11 49

**Comment by OgDev-01** [comment]
> @OgDev-01, you'll need to merge the lates from beta to grab @jpmcb's changes for insights. Currently I'm getting this error whe I pull down your latest code.
> 
> CleanShot 2023-12-21 at 09 11 49

I've merged to beta with the latest changes

**Review by nickytonline — APPROVED** [review]
:shipit:

**Review by brandonroberts — APPROVED** [review]
