### PR TITLE
fix: added a constant for our fallback empty data value

### LINKED ISSUE #2375: Refactor: Create a constant for empty data value "-"
Create a constant for empty data value "-". We currently have it sprawled across the codebase.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

While working on #2373, I added a fallback value that we use, `-`. It was all over the codebase so I created a constant for it to keep things uniform.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Relates to #2373
Fixes #2375

## Steps to QA

N/A

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/molecules/ContributorListTableRow/contributor-list-table-row.tsx [hunk 1]
```diff
@@ -158,11 +159,13 @@ const ContributorListTableRow = ({
 
           <div className="flex items-center justify-between py-3 border-b">
             <div>Languages</div>
-            {contributorLanguageList && (
-              <p>
+            {contributorLanguageList.length > 0 ? (
```
Comment (nickytonline) [inline components/molecules/ContributorListTableRow/contributor-list-table-row.tsx:162]: This is apart of #2373, so just waiting for that to get merged first.

File: lib/utils/fallbackValues.ts [hunk 2]
```diff
@@ -0,0 +1 @@
+export const DATA_FALLBACK_VALUE = "-";
```
Comment (nickytonline) [inline lib/utils/fallbackValues.ts:1]: I'll use this in #2373 as well once this is merged.

**Review by jpmcb — APPROVED** [review]
