### PR TITLE
fix: toggling hide bots for yolo coders no longer causes page jumps

### LINKED ISSUE #3910: Bug: Toggling hide bots on lottery factor on repository page causes page to jump back to the top
Toggling the hide bots on lottery factor on a repository page causes the page to jump back to the top.

You can see an example of this for the [remix-run/remix](https://app.opensauced.pizza/s/remix-run/remix?hideBots=false) repository page.

CleanShot 2024-08-10 at 16 39 33

The hidebots state is in the querystring (a good thing), e.g. https://app.opensauced.pizza/s/remix-run/remix?hideBots=false, but we're not leveraging the Next.js router's keep scroll position setting.

This can be leverage using the `setQueryParams` function, e.g. https://github.com/open-sauced/app/blob/b79f9746e7715287506d8d8723d28bac60bf073b/pages/workspaces/%5BworkspaceId%5D/contributor-insights/%5BlistId%5D/overview.tsx#L114

Also, the `useState` code for managing this state can be removed, i.e. https://github.com/open-sauced/app/blob/b79f9746e7715287506d8d8723d28bac60bf073b/pages/s/%5Borg%5D/%5Brepo%5D/index.tsx#L99-L101

as well as the `useEffect` code.

https://github.com/open-sauced/app/blob/b79f9746e7715287506d8d8723d28bac60bf073b/pages/s/%5Borg%5D/%5Brepo%5D/index.tsx#L109-L111

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now toggling hide bots for yolo coders in the lottery factor widget no longer causes page jumps.

## Related Tickets & Documents

Fixes #3910

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-08-10 at 16 39 33

**After**

CleanShot 2024-08-10 at 17 02 37

## Steps to QA

1. Go to a repository with yolo coders, e.g. the [remix-run/remix](https://app.opensauced.pizza/s/remix-run/remix?hideBots=false) repository page.
2. Click on the yolo coders button on the lottery factor widget
3. Scroll the page down a bit.
4. Toggle the hide bots setting a couple of times.
5. Notice the page no longer jumps.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

File: pages/s/[org]/[repo]/index.tsx [hunk 1]
```diff
@@ -96,19 +97,17 @@ export default function RepoPage({ repoData, ogImageUrl }: RepoPageProps) {
...
   const tabList = [
     { name: "Overview", path: "" },
     { name: "Contributors", path: "contributors" },
   ];
 
-  useEffect(() => {
-    router.push({ query: { ...router.query, hideBots: yoloHideBots } });
-  }, [yoloHideBots]);
+  function setYoloHideBots(value: boolean) {
+    setQueryParams({ hideBots: `${value}` });
```
Comment (nickytonline) [inline pages/s/[org]/[repo]/index.tsx:109]: `setQueryParams` is pushing to the Next.js router like in the code prior to this change, but it defaults to maintaining the scroll position.

https://github.com/open-sauced/app/blob/86be85ceec2a31a85530d9b8dd96c147bd20c3bb/lib/utils/query-params.ts#L11-L31

**Review by jpmcb — APPROVED** [review]
