### PR TITLE
fix: popover display issue of safari

### LINKED ISSUE #1144: Bug: unable to edit date on editing a highlight (Safari Only)
### Describe the bug

https://user-images.githubusercontent.com/237133/236319313-b8c3746d-077d-471c-9ca4-5be5068ec2b1.mov

### Steps to reproduce

1. Add a new highlight without date
1. Edit highlight and try to set date

### Affected services

insights.opensauced.pizza

### Platforms

_No response_

### Browsers

_No response_

### Environment

Production, Development, Testing

### Additional context

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR is a hacky fix to the radix popover and dialog issue in safari

### What i did
- refactored the popover to use a predefined `useState` to handle the open and close state manually
- set the open state to `true` on icon click
- added a `mousedown` event listener to the document to know detect when a user clicks outside the popover content so i can set the open state to `false`.
- also added an addition `useEffect` to set the open state to `false` when users select a date( can be reverted if it is not necessary)

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
fixes #1144

### Before

https://github.com/open-sauced/app/assets/62995161/cb11c435-9bf8-4e61-860b-910c8535f882

### After
https://github.com/open-sauced/app/assets/62995161/ea14a093-a818-4da5-9bff-796b8e6ff265

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by OgDev-01** [comment]
Just remembered we have this also in the create highlight form... adding this fix there shortly

**Comment by OgDev-01** [comment]
This is good for review now @open-sauced/engineering

File: components/molecules/HighlightInput/highlight-input-form.tsx [hunk 1]
```diff
@@ -555,14 +575,20 @@ const HighlightInputForm = ({ refreshCallback }: HighlightInputFormProps): JSX.E
...
               <div className="flex w-full gap-1 items-center">
                 <Tooltip direction="top" content="Pick a date">
-                  <Popover>
+                  <Popover open={createPopoverOpen}>
                     <PopoverTrigger asChild>
-                      <button className="flex items-center gap-2 p-2 text-base rounded-full text-light-slate-9 bg-light-slate-3">
+                      <div
+                        onClick={() => {
+                          setCreatePopoverOpen(true);
+                          console.log("::::: ", createPopoverOpen);
```
Comment (brandonroberts) [inline components/molecules/HighlightInput/highlight-input-form.tsx:583]: nit: remove console.log
```suggestion
```

**Review by brandonroberts — APPROVED** [review]

File: components/molecules/ContributorHighlight/contributor-highlight-card.tsx [hunk 2]
```diff
@@ -166,6 +168,25 @@ const ContributorHighlightCard = ({
     return !matches ? false : true;
   };
 
+  const handleClickOutsidePopoverContent = (e: MouseEvent) => {
+    if (popoverContentRef.current && !popoverContentRef.current.contains(e.target as Node)) {
+      setPopoverOpen(false);
+    }
+  };
+
+  useEffect(() => {
```
[the remark this answers is not in the document]
Comment (OgDev-01) [reply components/molecules/ContributorHighlight/contributor-highlight-card.tsx:177]: Thanks! 🙏 . done

[the remark this answers is not in the document]
Comment (nickytonline) [reply components/molecules/ContributorHighlight/contributor-highlight-card.tsx:177]: Going to take it for a test drive

File: components/molecules/HighlightInput/highlight-input-form.tsx [hunk 3]
```diff
@@ -441,7 +457,7 @@ const HighlightInputForm = ({ refreshCallback }: HighlightInputFormProps): JSX.E
         setBodyText("");
         setHighlightLink("");
         setDate(undefined);
-        setIsDivFocused(false);
+        setDialogOpen(false);
```
Comment (nickytonline) [inline components/molecules/HighlightInput/highlight-input-form.tsx:460]: These changes are good like we discussed in our pairing session yesterday, but they are not related to the fix.

Create a separate PR for moving `setIsDivFocused` -> `setDialogOpen` and `isDivFocused` -> `dialogOpen`.

**Review by nickytonline — CHANGES_REQUESTED** [review]

**Review by nickytonline — COMMENTED** [review]
Once the unrelated refactor changes are reverted, this is good to go.

We should look into encapsulating the fix you made here into a component so that we can reuse this elsewhere if we need a `<Popover />` again in a dialog, but let's wait until that happens.

File: components/molecules/HighlightInput/highlight-input-form.tsx [hunk 4]
```diff
@@ -555,20 +571,28 @@ const HighlightInputForm = ({ refreshCallback }: HighlightInputFormProps): JSX.E
             <div className="flex">
               <div className="flex w-full gap-1 items-center">
                 <Tooltip direction="top" content="Pick a date">
-                  <Popover>
+                  <Popover open={createPopoverOpen}>
                     <PopoverTrigger asChild>
-                      <button className="flex items-center gap-2 p-2 text-base rounded-full text-light-slate-9 bg-light-slate-3">
+                      <div
```
Comment (nickytonline) [inline components/molecules/HighlightInput/highlight-input-form.tsx:576]: refactor (blocking): this needs to stay as a button so that it can receive focus.

**Review by nickytonline — CHANGES_REQUESTED** [review]

**Review by jpmcb — APPROVED** [review]
From a QA perspective, looks good on Safari!

**Review by nickytonline — APPROVED** [review]
Thanks for making the changes @OgDev-01!

:shipit:

**Review by nickytonline — APPROVED** [review]
Thanks for making the changes @OgDev-01!

:shipit:
