### PR TITLE
fix: repos with long name partially stack

### LINKED ISSUE #2335: Bug: Long repos' name are partially stack at the back when searching using search input in the Explore tab
### Describe the bug

When I searched for repos using the search input in the "Explore" tab, long repos' names are partially stacked at the back of another name as shown in the screen recording below.
 
search repo

### Steps to reproduce

1. Go to the "Explore" tab.
2. Choose a language from the dropdown menu.
3. Search for any repository in the search input. For example, "gpt".
4. Scroll down. You will see longer repos' name are partially stacked behind other name.  

### Browsers

Chrome

### Additional context (Is this in dev or production?)

Production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [ ] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by adiati98**
## Description

This PR fixes the long repos' names that are partially stacked at the back of another name in the search input of the Explore tab.

### The changes made here:

-  Add Tailwind className:
   ~- [`truncate`](https://tailwindcss.com/docs/text-overflow#truncate) to truncate overflowing text.~
   ~- [`tracking-tighter`](https://tailwindcss.com/docs/letter-spacing) to reduce letter spacing for better space.~
   - `inline-block` to the `<span>` .

- Remove Tailwind classNames:
   - `overflow-hidden` ~as it's [included in the `truncate`](https://tailwindcss.com/docs/text-overflow)~.
   - `break-all` as we don't want to add line breaks.

**Note:** Changes made based on [this conversation](https://github.com/open-sauced/app/pull/2534#issuecomment-1919170734).

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2335 

### Before

search before

### After

final changes app

~### After~

search after

## Steps to QA

1. Go to https://opensauced.pizza/ and sign in.
2. Click the "Explore" tab.
3. Type, for example, "gpt" in the "Search Repository" input.
4. You can see repos with long name are no longer stack on top of other repo's name.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] What gif best describes this PR or how it makes you feel?

finally gif

### CODE REVIEW

**Review by takanome-dev — COMMENTED** [review]
Wonder why there is no ellipsis after the text is truncated but another solution is to add `inline-block` in the `span` classes

SCR-20240126-itmr

**Comment by adiati98** [comment]
> Wonder why there is no ellipsis after the text is truncated but another solution is to add `inline-block` in the `span` classes
> 
> SCR-20240126-itmr

@takanome-dev I follow your suggestion and made the changes as below:
- Added `inline-block` className to the `span`.
- Removed the `truncate` and `tracking-tighter` as they are no longer necessary.

---

I've tried several things and I found that only longer **repo** names are truncated and have ellipsis. But the longer **owner** names stay as is. That's why for longer owner names, ellipsis are not showing.

truncate

It will take me a while to figure this out if you want to have the `suggestion` in one line and ellipsis, and I don't want to hold this issue back. So, feel free to unassign me and give this to someone else. Thank you. 😊

cc: @nickytonline

**Comment by takanome-dev** [comment]
Hey @adiati98, the changes looks good to me 👍 Let's hear what @open-sauced/engineering  think about it

**Review by nickytonline — COMMENTED** [review]
We definitely want each item in the list to be on one line and contain `...` if it's too long. I'm wrapping up some feature work atm, but if you're still stuck on this @adiati98, I can take a peek to provide suggestions.

**Comment by adiati98** [comment]
I'm honestly still stuck if we want to do ellipsis, @nickytonline .
Because ellipsis only applies to a longer repository name, but not the longer organization name. 

When there's a longer organization name, they will stack on top of each other. And I haven't found a solution for this.

**Comment by adiati98** [comment]
@nickytonline I've made the changes as per [Bekah's suggestion](https://github.com/open-sauced/app/issues/2335#issuecomment-1997612195) to apply width in the `<span>`. 

It didn't work for the longer organization name when I tried earlier (before my last commit) as I mentioned in [this comment](https://github.com/open-sauced/app/pull/2534#issuecomment-1919170734).

But after setting the width, it now works! The longer organization names are not in two lines as shown below.

Screenshot 2024-03-15 095905

However, as a note, for very long organization name, there's only ellipsis shown for the repo name as below.

Screenshot 2024-03-15 202258

File: components/atoms/Search/search.tsx [hunk 1]
```diff
@@ -154,7 +151,13 @@ const Search = ({
                   suggestion && handleOnSelect(suggestion);
                 }}
               >
-                {typeof suggestion === "string" ? <span className="pl-5 text-sm ">{suggestion}</span> : suggestion.node}
+                {typeof suggestion === "string" ? (
+                  <span className="pl-5 text-sm sm:max-w-[12.3rem] md:max-w-[11rem]md:mw-auto inline-block text-ellipsis truncate tracking-tighter">
```
Comment (nickytonline) [inline components/atoms/Search/search.tsx:155]:
```suggestion
                  <span className="pl-5 text-sm md:mw-auto inline-block text-ellipsis truncate tracking-tighter">
```

File: components/atoms/Search/search.tsx [hunk 2]
```diff
@@ -142,10 +142,7 @@ const Search = ({
             {suggestionsLabel && suggestions.length > 0 ? <div className="pl-5 pt-4">{suggestionsLabel}</div> : null}
             {suggestions.map((suggestion, index) => (
               <div
-                className={clsx(
-                  cursor === index && "_cursorActive bg-slate-100",
-                  "px-4 py-2 overflow-hidden break-all hover:bg-light-slate-2"
-                )}
+                className={clsx(cursor === index && "_cursorActive bg-slate-100", "px-4 py-2 hover:bg-light-slate-2")}
```
Comment (nickytonline) [inline components/atoms/Search/search.tsx:145]: refactor (blocking): Instead of styling each span, configure it for all spans in it's parent.

```suggestion
                className={clsx(cursor === index && "_cursorActive bg-slate-100", "px-4 py-2 hover:bg-light-slate-2", "[&_span]:max-w-[12.3rem]")}
```

Is `md:max-w-[11rem]` required @adiati98? I'm only asking as the value is smaller for a larger screen.

Comment (adiati98) [reply components/atoms/Search/search.tsx:145]: @nickytonline let me check it locally and get back to you.

File: components/atoms/Search/search.tsx (hunk 1 above)
Comment (adiati98) [reply components/atoms/Search/search.tsx:155]: I've committed this locally after testing.

File: components/atoms/Search/search.tsx (hunk 2 above)
Comment (adiati98) [reply components/atoms/Search/search.tsx]: @nickytonline I've tested the suggestions locally, committed, and pushed them. We don't need the `md:max-w-[11rem]`.
Below is the screenshot of the result. The blue box is longer repo name is truncated. And the green box is longer organization name, with the whole repo name gets truncated.

Screenshot 2024-04-04 201804

**Review by nickytonline — APPROVED** [review]
This looks great @adiati98, could we make the 12.3 rem a little bit bigger, like 12.4 or 12.5 or does it get cut off (not ellipsis) at 12.4?

**Comment by adiati98** [comment]
@nickytonline making `12.3 rem` to `12.4 rem` or `12.5 rem` do almost the same result, where the longer organization name gets the whole repo name truncated.

However, I tried two sizes:

1. With `13 rem`, and the result is better. The suggestion with longer repo name is shown longer before gets truncated (in the blue box) and the longer organization name can get at least a letter before gets truncated (green box).

   

2. With `13.4 rem`. Longer organization name has three letters before gets truncated. However, bigger than this caused getting cut off.

**Comment by nickytonline** [comment]
> @nickytonline making `12.3 rem` to `12.4 rem` or `12.5 rem` do almost the same result, where the longer organization name gets the whole repo name truncated.
> 
> 
> 
> However, I tried two sizes:
> 
> 
> 
> 1. With `13 rem`, and the result is better. The suggestion with longer repo name is shown longer before gets truncated (in the blue box) and the longer organization name can get at least a letter before gets truncated (green box).
> 
> 
> 
>    
> 
> 
> 
> 2. With `13.4 rem`. Longer organization name has two letters before gets truncated. However, bigger than this caused getting cut off.
> 
> 
> 
>    
> 
> 
> 
> 
> 
> 

The 13rem one looks good. Thanks for your patience in this @adiati98!

**Comment by adiati98** [comment]
@nickytonline thank you also for your patience going back and forth with this! 🙏

I'm not on my computer anymore. So, either I'll fix it tomorrow or if you can do it, Nick. 😊

**Comment by nickytonline** [comment]
> @nickytonline thank you also for your patience going back and forth with this! 🙏
> 
> I'm not on my computer anymore. So, either I'll fix it tomorrow or if you can do it, Nick. 😊

No rush. Whenever you have a chance to push the changes.

**Review by brandonroberts — APPROVED** [review]
