### PR TITLE
fix: now workspace pages that crash when you don't have access to them give a page not found instead

### LINKED ISSUE #2693: Bug: When a user doesn't have access to a workspace, it gives a 500 error
Currently pages that give a 401 actually throw a 500 error. If the status code from the API is 401, we should return a 404.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now instead of giving an HTTP 500 (internal server error) when someone doesn't have access to a workspace page, it returns a 404 (page not found) instead.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2693

## Steps to QA

1. Ensure you're logged in.
2. Navigate to e.g. https://deploy-preview-2694--oss-insights.netlify.app/workspaces/ff1160b5-cc32-45de-8e21-dd7b64f84a74/repositories (@brandonroberts workspace). If you're testing @brandonroberts, head to mine, https://deploy-preview-2694--oss-insights.netlify.app/workspaces/3432aaf7-55db-4c2b-9fde-f61604471e21/repositories
3. A 404 page loads

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: pages/workspaces/[workspaceId]/contributor-insights/new.tsx [hunk 1]
```diff
@@ -350,7 +352,9 @@ export const getServerSideProps = async (ctx: GetServerSidePropsContext) => {
   });
 
   if (error) {
-    if (error.status === 404) {
+    deleteCookie(ctx.res, WORKSPACE_ID_COOKIE_NAME);
```
Comment (nickytonline) [inline pages/workspaces/[workspaceId]/contributor-insights/new.tsx:355]: Some cookie deletions were missing.

**Review by brandonroberts — APPROVED** [review]

File: pages/workspaces/[workspaceId]/contributor-insights/index.tsx [hunk 2]
```diff
@@ -33,7 +35,9 @@ export const getServerSideProps = async (context: GetServerSidePropsContext) =>
   });
 
   if (error) {
-    if (error.status === 404) {
+    deleteCookie(context.res, WORKSPACE_ID_COOKIE_NAME);
+
+    if (error.status === 404 || error.status === 401) {
       return { notFound: true };
     }
```
Comment (nickytonline) [inline pages/workspaces/[workspaceId]/contributor-insights/index.tsx:42]: not sure if it's worth it, but maybe wrapping up this same logic in all these pages into a function might make sense. Not for this PR though.

**Review by jpmcb — APPROVED** [review]
![]](https://media.giphy.com/media/v1.Y2lkPTc5MGI3NjExNzhnZ2lwNnE4NnQxNGpkOGI3bHplbmlhYjI1eGk5aHdiM3VtNnFwYSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/3oFzlV2pq0nnFntAZ2/giphy.gif)
