### PR TITLE
fix: now the error message in highlight form will alert assistive tech

### LINKED ISSUE #2009: Bug: error messages in highlight form not notifying screen readers
### Describe the bug

When you create a new highlight and there are errors, currently the errors do not alert a screen reader.

### Steps to reproduce

1. Ensure you're logged in to app.opensauced.pizza
2. Go to `http://app.opensauced.pizza/user/your_user_name?tab=highlights`
3. If on macOS, press Cmd + F5 to start voice over.
4. Try submitting the form.
5. Notice that Voice Over is not alerted of the error.

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Error messages in the highlight form were not notifying assistive tech like a screen reader. I came across this while a new error message was added in #2007.

I'm not sure how to record my screen with Voice Over on, but I can confirm it alerts the screen reader now.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2009

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/molecules/HighlightInput/highlight-input-form.tsx [hunk 1]
```diff
@@ -526,11 +526,16 @@ const HighlightInputForm = ({ refreshCallback }: HighlightInputFormProps): JSX.E
           </DialogHeader>
           <DialogCloseButton onClick={() => setIsDivFocused(false)} />
           <form onSubmit={handlePostHighlight} className="flex flex-col gap-4 font-normal">
-            {errorMsg && (
-              <p className="inline-flex items-center gap-2 px-2 py-1 text-red-500 bg-red-100 border border-red-500 rounded-md w-full text-sm">
-                <MdError size={20} /> {errorMsg}
-              </p>
-            )}
+            <p
+              role="alert"
```
Comment (nickytonline) [inline components/molecules/HighlightInput/highlight-input-form.tsx:530]: More info on [role="alert" on MDN](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/alert_role).

**Review by brandonroberts — APPROVED** [review]
