### PR TITLE
fix: smaller screen fixes for workspaces

### LINKED ISSUE #2632: fix: small screen improvements for workspaces
Some cleanup to the workspaces flows needs to be done for smaller screens

- [x] #2628
- [x] #2738
- [x] #2745
- [x] #2740
- [x] #2752

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now workspaces work well for smaller screen experiences.

High-level what was done:
- now 30% width for the first column of the repositories table for large screens only
- Fixed some styling for the tabs list
- Workspaces header was causing issues with long text for workspace names even though it was being truncated already and used ellipsis. Now, the font is smaller on medium and below screens and the max length is smaller on smaller screens.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2632

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-02-27 at 08 47 21

**After**

CleanShot 2024-02-27 at 08 46 04

## Steps to QA

1. Ensure you're logged in.
2. Go to any workspace and try it on smaller screens.
3. Notice there is no horizontal scrolling and all the content is visible.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by bdougie — APPROVED** [review]

File: layouts/hub-page.tsx [hunk 1]
```diff
@@ -28,60 +26,56 @@ const HubPageLayout = ({ page = "dashboard", children }: { page?: string; childr
   const canEdit = membership && ["edit", "admin"].includes(membership.access);
 
   return (
-    <div className={workspaceId && "flex flex-col min-h-screen"}>
-      <TopNav />
```
Comment (nickytonline) [inline layouts/hub-page.tsx:32]: The `<TopNav />` is already in the workspaces layout.

**Review by brandonroberts — APPROVED** [review]
