### PR TITLE
fix: now suggestion prompts run immediately

### LINKED ISSUE #3241: fix: suggestion prompt should run immediately
Suggestion prompts should run immediately instead of populating the prompt input. This is how ChatGPT works.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now suggestion prompts in StarSearch run immediately.

## Related Tickets & Documents

Fixes #3241

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-04-24 at 17 35 29

**After**

Note the double render is because of React strict mode during dev.

CleanShot 2024-04-24 at 17 34 35

## Steps to QA

1. Go to `/star-search`
2. Click on a suggestion.
3. The suggestion populates the prompt input and StarSearch begins to respond immediately.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

File: pages/star-search/index.tsx [hunk 1]
```diff
@@ -52,13 +52,27 @@ type StarSearchChat = {
...
 
+  function addPromptInput(prompt: string) {
+    if (!inputRef.current?.form) {
+      return;
+    }
+
+    inputRef.current.value = prompt;
+    const { form } = inputRef.current;
+
+    if (typeof form.requestSubmit === "function") {
```
Comment (nickytonline) [inline pages/star-search/index.tsx:69]: form.submit() wasn't working but not with the [synthetic events in React](https://react.dev/reference/react-dom/components/common#react-event-object), so I went with this. See https://github.com/facebook/react/issues/6796#issuecomment-594081509

**Review by brandonroberts — APPROVED** [review]

**Review by isabensusan — APPROVED** [review]
bon-appetit-gourmet-gif-by-studios-2016
