### PR TITLE
fix: new highlight dialog ui breaks now fixed

### LINKED ISSUE #2086: Bug: create new highlight dialog breaks when rendering OG images
### Describe the bug

https://github.com/open-sauced/app/assets/62995161/5f98c2c9-d426-4a51-b4ae-27a63d54f9a4

### Steps to reproduce

1. Goto https://beta.app.opensauced.pizza/feed
2. login and try creating a new highlight

### Browsers

Chrome

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR fixes a strange ui breaks with the create highlight dialog 

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
fixes #2086 

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/62995161/83a1cada-12c4-402c-90ad-8b3e0e38dbfd

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/molecules/HighlightInput/highlight-input-form.tsx [hunk 1]
```diff
@@ -527,7 +527,7 @@ const HighlightInputForm = ({ refreshCallback }: HighlightInputFormProps): JSX.E
         }}
         open={isDivFocused}
       >
-        <DialogContent className="p-4 w-full md:w-[33rem] xs:w-[25rem] max-h-[80vh]">
+        <DialogContent className="p-4 w-full md:w-[40rem] xs:w-[25rem] max-h-[80vh] overflow-y-scroll">
```
Comment (nickytonline) [inline components/molecules/HighlightInput/highlight-input-form.tsx:530]: I don't think we need `md:w-[40rem] xs:w-[25rem]`. I removed them and it still looked fine. We could add `m-4` except for a small screen and that should be fine.

Comment (OgDev-01) [reply components/molecules/HighlightInput/highlight-input-form.tsx:530]: Taking those off makes the content grow to the screen because we have a default of w-full set in the root here https://github.com/open-sauced/app/blob/2b7b61391d73081ea1fcb403ccb1883b636220ad/components/molecules/Dialog/dialog.tsx#L56

image

Comment (nickytonline) [reply components/molecules/HighlightInput/highlight-input-form.tsx:530]: Maybe use `w-max` instead of `w-full`? If not, we'll keep as is. Just trying to avoid the Tailwind anti-pattern of explicit values.

**Review by nickytonline — APPROVED** [review]
🚀

**Review by brandonroberts — APPROVED** [review]
