### PR TITLE
fix: activity list contributions treemap nodes are keyboard navigable now

### LINKED ISSUE #2389: Bug: contributions treemap nodes are not keyboard navigable
The contributions treemap currently uses `<animated.div />`s. Replace them with `<animated.button />`s so that nodes in the contributions treemap are keyboard navigable and if you press enter when one is focused, it will drill down to the next level.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

`<animated.div />`s have been replaced with `<animated.button />`s so that nodes in the contributions treemap are keyboard navigable and if you press enter when one is focused, it will drill down to the next level.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2389 
Relates to #2175

## Mobile & Desktop Screenshots/Recordings

CleanShot 2023-12-21 at 08 06 52

## Steps to QA

1. Ensure you're logged in.
2. Navigate to https://deploy-preview-2388--oss-insights.netlify.app/lists/767e8678-c092-4727-b5ce-d809e851ef53/activity
3. Use the tab key on the list activity page and you will eventually get to the contributions treemap. Keep tabbing and notice the nodes get focus.
4. Press enter and it drills down to the contributor level.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/molecules/TreemapPrototype/contributor-node.tsx [hunk 1]
```diff
@@ -18,7 +18,7 @@ const NonMemoizedContributorNode = <Datum extends { id: string; value?: number;
   const avatarURL = getAvatarByUsername(node.id);
 
   return (
-    <animated.div
+    <animated.button
```
Comment (nickytonline) [inline components/molecules/TreemapPrototype/contributor-node.tsx:21]: By making this a button, it is able to receive focus and be keyboard navigable.

File: components/molecules/TreemapPrototype/special-node.tsx [hunk 2]
```diff
@@ -26,6 +26,7 @@ const NonMemoizedSpecialNode = <Datum extends object>({
         borderWidth,
         borderColor: node.borderColor,
       }}
+      onClick={node.onClick}
```
Comment (nickytonline) [inline components/molecules/TreemapPrototype/special-node.tsx:29]: I moved the click here to drill down to the next level with the keyboard. The event probably bubbles down, but it makes more sense that the click is at the top level.

**Review by brandonroberts — APPROVED** [review]

**Review by jpmcb — APPROVED** [review]
