### PR TITLE
fix: decreased delay time of tooltips

### LINKED ISSUE #1924: Bug: Tooltips in the App Take Too Long to Open
### Describe the bug

Currently, it takes alomst 3/4 of a second for a tooltip to open.

### Steps to reproduce

1. Navigate to https://app.opensauced.pizza/lists/ab4c5807-e2bc-495c-90c9-9186611e1535/activity
2. Hover over a bar in the most active contributors graph. Notice the delay.

CleanShot 2023-10-17 at 11 11 49

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

@isabensusan noticed that tooltips appearing across the app were slow. Before the delay was 700ms. Now it's 300ms.

**Before**

CleanShot 2023-10-17 at 11 11 49

**After**

CleanShot 2023-10-17 at 11 16 23

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1924

## Added tests?

- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/atoms/Tooltip/tooltip.tsx [hunk 1]
```diff
@@ -14,7 +14,7 @@ const Tooltip = ({ children, content, className, direction }: TooltipProps): JSX
   const { Portal, Root, Content, Trigger, Arrow } = TooltipPrimitive;
 
   return (
-    <Root>
+    <Root delayDuration={300}>
```
Comment (nickytonline) [inline components/atoms/Tooltip/tooltip.tsx:17]: The Radix tooltip `<Root />` component's `delayDuration` prop's default value is 700ms. See https://www.radix-ui.com/primitives/docs/components/tooltip#provider

**Review by OgDev-01 — APPROVED** [review]
🍕

**Review by isabensusan — COMMENTED** [review]
lgtm 👍

**Review by isabensusan — APPROVED** [review]
