### PR TITLE
fix: now you can click on a contributor highlight OG image to go to the referenced url

### LINKED ISSUE #26: [Refactor] Revert changes that removed disabled prop on Tool Nav
Need to reimplement disabled functionality for this component: https://github.com/open-sauced/insights/blob/61f82f19f9990200983b682a3f34213ff11c60a1/components/organisms/toolist/nav.tsx#L22

`disabled={navbarTool === tool.name}`

### LINKED ISSUE #2445: Feature: Make OG image in contributor highlight card a link
Contributor highlight cards provide a link to the referenced URL in a highlight, but it's pretty common to be able to click an OG image to load the page it's referring to.

**Current behaviour**

CleanShot 2024-01-09 at 08 57 49

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now OG images in contributor highlight cards can be clicked and take you to the referenced URL in the highlight.

## What type of PR is this? (check all applicable)

- [x] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Closes #2445

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-01-09 at 08 57 49

**After**

CleanShot 2024-01-09 at 09 03 06

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/molecules/ContributorHighlight/contributor-highlight-card.tsx [hunk 1]
```diff
@@ -614,11 +614,13 @@ const ContributorHighlightCard = ({
       </div>
 
       {/* Generated OG card section */}
-      {type === "pull_request" || type === "issue" ? (
-        <GhOpenGraphImg githubLink={highlightLink} />
-      ) : (
-        <DevToSocialImg blogLink={highlightLink} />
-      )}
+      <a href={highlightLink} target="_blank" rel="noreferrer" aria-hidden="true">
```
Comment (nickytonline) [inline components/molecules/ContributorHighlight/contributor-highlight-card.tsx:617]: `aria-hidden` is used here so that a screen reader or other assistive technology doesn't need to see a repeat of the same link.

**Review by OgDev-01 — APPROVED** [review]
LG 🍕

**Review by brandonroberts — APPROVED** [review]
