### PR TITLE
fix: fixed contributor insight contributor grid not loading paged data

### LINKED ISSUE #3944: Bug: Can't change pages to see next contrib list
### Describe the bug

When trying to go to the next page in the contributor list, nothing happens. 

https://github.com/user-attachments/assets/b180a414-393b-4d42-90eb-7d1855d413d1

### Steps to reproduce

1. go to [https://app.opensauced.pizza/workspaces/69c010b5-222b-4028-b61f-842484aac012/contributor-insights/7a4c0139-f849-43ea-84b8-a0db042e6056/overview?page=1](https://app.opensauced.pizza/workspaces/69c010b5-222b-4028-b61f-842484aac012/contributor-insights/7a4c0139-f849-43ea-84b8-a0db042e6056/overview?page=1)
2. click next
3. see the same contributors

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now, the contributor insight contributor grid on the overview page pages data again in the grid. When moving to the new grid, `setPage` on the `useContributorsList` hook was no longer being used, so the data fetching wasn't fetching new data as the page wasn't being updated even though it was updated in the browser URL bar.

## Related Tickets & Documents

Fixes #3944

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-08-13 at 23 31 00

**After**

CleanShot 2024-08-13 at 23 28 54

## Steps to QA

1. Go to a contributor insight overview page, e.g. https://deploy-preview-3945--oss-insights.netlify.app/workspaces/3432aaf7-55db-4c2b-9fde-f61604471e21/contributor-insights/aaf5ec66-9d3a-456d-b62b-05410e0b2fa4/overview
2. In the grid page selection underneath the grid, click on `2`.
3. Notice the grid updates to the second page of contributors.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

File: lib/hooks/api/useContributorList.ts [hunk 1]
```diff
@@ -43,16 +42,14 @@ export const useContributorsList = ({
     data: DbPRContributor[];
     meta: Meta;
   };
-  initialPage?: number;
+  page: number;
```
Comment (nickytonline) [inline lib/hooks/api/useContributorList.ts:45]: no longer optional as we want to depend on it being passed in from the querystring.

**Review by brandonroberts — APPROVED** [review]

**Review by BekahHW — APPROVED** [review]
