### PR TITLE
fix: set `/star-search` user avatar after logging in

### LINKED ISSUE #3523: Bug: Avatar link broken when logged out user logs in on StarSearch page
If you're logged in, your avatar for StarSearch always appears.

CleanShot 2024-06-05 at 07 37 06

However, if you start from a logged out experience and log in, your avatar is broken.

CleanShot 2024-06-05 at 07 42 25

This wasn't an issue before, but now that we let users access `/star-search` and prompt them to log in if not logged in it's broken because we're retrieving the `userId` via `getServerSideProps` which only renders those props on the initial page load. The `userId` prop should be promoted to a variable within the component to handle the logged out then logged in scenario.

### PR DESCRIPTION
**Pull request by zeucapua**
## Description

Added a `useMemo` to set the user ID based on the session. This fixes the issue where it doesn't render any image if the user starts logged out in the StarSearch page then logs in when prompted.

## Related Tickets & Documents

Closes #3523 

## Mobile & Desktop Screenshots/Recordings

https://github.com/open-sauced/app/assets/20603494/dffdf510-951e-4f78-a045-0161fe8893d9

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

File: pages/star-search/index.tsx [hunk 1]
```diff
@@ -189,7 +190,9 @@ export default function StarSearchPage({ userId, ogImageUrl }: StarSearchPagePro
   const scrollRef = useRef<HTMLDivElement>(null);
   const { feedback, prompt } = useStarSearchFeedback();
   const { toast } = useToast();
+  const { session } = useSession(true);
   const { sessionToken: bearerToken } = useSupabaseAuth();
+  const userId = useMemo(() => (session ? session.id : initialUserId), [session]);
```
Comment (nickytonline) [inline pages/star-search/index.tsx:195]: There will only ever be the currently logged in user here. `useMemo` seems unnecessary as this is not an expensive calculation.

File: pages/star-search/index.tsx [hunk 2]
```diff
@@ -178,7 +179,7 @@ function StarSearchWidget({ widgetDefinition }: { widgetDefinition: WidgetDefini
   );
 }
 
-export default function StarSearchPage({ userId, ogImageUrl }: StarSearchPageProps) {
+export default function StarSearchPage({ userId: initialUserId, ogImageUrl }: StarSearchPageProps) {
```
Comment (nickytonline) [inline pages/star-search/index.tsx:182]: No need to have an `initialUserId`. We can remove the server-side prop for the userId and manage it only on the client-side.

**Review by nickytonline — CHANGES_REQUESTED** [review]

**Review by brandonroberts — APPROVED** [review]

**Review by nickytonline — APPROVED** [review]
Works great! 🚢
