### PR TITLE
fix: now range filter works on list contributors page grid view

### LINKED ISSUE #1818: Bug: Range filter does nothing on the List Contributors page in Grid View
### Describe the bug

The range filter does nothing on the List Contributors page.

### Steps to reproduce

1. Navigate to the list contributors page, e.g. https://beta.insights.opensauced.pizza/lists/23c2ca69-7667-4b6a-ad2e-d402999af310/contributors
2. Click on the range filter switching between 7, 30, and 90 days. Notice the grid view does not change.

The mobile card view works fine.

CleanShot 2023-10-06 at 08 41 26

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

I came across this while looking at the range filter rework in #1815. Now the range filter works for the grid view.

You can see it working here, https://deploy-preview-1819--oss-insights.netlify.app/lists/23c2ca69-7667-4b6a-ad2e-d402999af310/contributors

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
Relates to #1734
Fixes #1818

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2023-10-06 at 08 41 26

**After**

CleanShot 2023-10-06 at 08 44 16

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/molecules/ContributorListTableHeader/contributor-list-table-header.tsx [hunk 1]
```diff
@@ -60,7 +65,7 @@ const ContributorListTableHeaders = ({ selected, handleOnSelectAllContributor }:
           <TableTitle>Contributions</TableTitle>
         </div>
         <div className={clsx(classNames.cols.contributors, "hidden lg:flex justify-center")}>
-          <TableTitle>Last 30 Days</TableTitle>
+          <TableTitle>{`Last ${range} Days`}</TableTitle>
```
Comment (nickytonline) [inline components/molecules/ContributorListTableHeader/contributor-list-table-header.tsx:68]: This header changes according to the range specified now.

File: components/molecules/ContributorListTableHeader/contributor-list-table-header.tsx [hunk 2]
```diff
@@ -7,9 +7,14 @@ import Checkbox from "components/atoms/Checkbox/checkbox";
...
   selected?: boolean;
   handleOnSelectAllContributor?: (contributor: any) => void;
+  range?: number;
 }
 
-const ContributorListTableHeaders = ({ selected, handleOnSelectAllContributor }: ContributorListTableHeadersProps) => {
+const ContributorListTableHeaders = ({
+  selected,
+  handleOnSelectAllContributor,
+  range = 30,
```
Comment (nickytonline) [inline components/molecules/ContributorListTableHeader/contributor-list-table-header.tsx:16]: I default to `30` for the range so that existing views don't break.

File: components/molecules/ContributorListTableRow/contributor-list-table-row.tsx [hunk 3]
```diff
@@ -47,14 +48,15 @@ const ContributorListTableRow = ({
   topic,
   selected,
   handleOnSelectContributor,
+  range,
 }: ContributorListTableRow) => {
   const [tableOpen, setTableOpen] = useState(false);
 
   const { data: user } = useFetchUser(contributor.author_login);
-  const { data } = useContributorPullRequests(contributor.author_login, topic, [], 30);
+  const { data } = useContributorPullRequests(contributor.author_login, topic, [], range);
```
Comment (nickytonline) [inline components/molecules/ContributorListTableRow/contributor-list-table-row.tsx:56]: The range was being applied to the data.

File: lib/hooks/api/useContributorList.ts [hunk 4]
```diff
@@ -29,11 +30,18 @@ export const useContributorsList = ({
   };
   initialPage?: number;
   defaultLimit?: number;
+  defaultRange?: number;
 }) => {
+  const [range, setRange] = useState(defaultRange); // [start, end
   const [page, setPage] = useState(initialPage);
   const [limit, setLimit] = useState(defaultLimit);
+  const query = new URLSearchParams();
```
Comment (nickytonline) [inline lib/hooks/api/useContributorList.ts:38]: Now the data retrieved reflects the range.

**Review by OgDev-01 — APPROVED** [review]
