### PR TITLE
fix: fixed recommended repository link

### LINKED ISSUE #2363: Bug: Recommendation card in user profile routes to wrong location
### Describe the bug

Upon clicking the recommendation card in the user profile it opens a new tab with the URL `https://app.opensauced.pizza/hot/repositories/filter/some_owner/some_repo?range=30`
And there is no repo list available unless we click on dashboard tab.

So possible fix is to replace `repositories` path from the URL and add `dashboard` path instead which will select the dashboard tab as default and the page will have list of repos.

### Steps to reproduce

1. Go to Profile page
2. Select Recommendations tab
3. If you have any recommended repo then you can click on the card and it will route you to new tab and opens a new URL

routing bug #1

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by sourabpramanik**
## Description
The recommended card in user profile routes to a wrong location where no repositories list to be found because of the wrong path in the URL. This PR fixes the path and replaces the path `repository` with  `dashboard`

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [X] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
fixes #2363

## Mobile & Desktop Screenshots/Recordings
fix

## Steps to QA
1. Go to Profile page
2. Select Recommendations tab
3. If you have any recommended repo then you can click on the card and it will route you to new tab and opens a new URL

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [X] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

NO

## [optional] What gif best describes this PR or how it makes you feel?
pr

### CODE REVIEW

**Review by OgDev-01 — APPROVED** [review]
Thanks for this quick fix @sourabpramanik 🍕

**Comment by sourabpramanik** [comment]
adding a redirection in the middleware can solve as well.

File: components/molecules/RecommendedRepoCard/recommended-repo-card.tsx [hunk 1]
```diff
@@ -52,7 +52,7 @@ const RecommendedRepoCard = ({ fullName, className }: RecommendedRepoCardProps):
           <div className="flex flex-col gap-2 pb-3">
             <a
               className="text-xl font-semibold"
-              href={`https://app.opensauced.pizza/hot/repositories/filter/${fullName}`}
+              href={`https://app.opensauced.pizza/hot/dashboard/filter/${fullName}`}
```
Comment (OgDev-01) [inline components/molecules/RecommendedRepoCard/recommended-repo-card.tsx:55]: > Thanks for the fix @sourabpramanik but this should be caught by a redirect, right @OgDev-01?

@brandonroberts, thanks for catching that. this will be caught in the redirect, but will hit a 404 since the url pattern doesn’t match any dynamic route.

@sourabpramanik, here is a quick refactor to fix this
```suggestion
              href={`https://app.opensauced.pizza/${name}/dashboard/filter/recent`}
```
The goal is to enable users get clear insights on the repo they click on from the recommendations

**Review by OgDev-01 — CHANGES_REQUESTED** [review]

**Review by jpmcb — COMMENTED** [review]
The redirect makes sense to me: I approved the Netlify build so we should be able to validate it once it goes through! 📦

**Comment by brandonroberts** [comment]
Yea, I thought we had a redirect in place already, but its not added to the pages with the the filter. This will work for now

**Review by brandonroberts — APPROVED** [review]
