### PR TITLE
fix: now most used languages are truncated to a limit of two

### LINKED ISSUE #2233: Bug: overflowing Most "Used Languages" in list contributors tab
### Describe the bug

When viewing a list and going to the contributors tab, some of the fields overlap quite alot:

Screenshot 2023-11-29 at 8 58 51 AM

This _seems_ to be the "Most Used Languages" tab but that doesn't really make sense since that seems to be the interests for @OgDev-01 - very bizzare!

### Steps to reproduce

1. Go to a list
2. Go to the contributors
3. Notice the overflow

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR fixes the overflow in language with the contributors table

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
fixes #2233

### Before
image

### After
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/molecules/ContributorListTableRow/contributor-list-table-row.tsx [hunk 1]
```diff
@@ -48,12 +48,15 @@ function getTopContributorLanguages(contributor: DbUser) {
...
+    return contributor.interests.split(",").slice(0, 2);
   }
-  return entries
-    .sort(([, a], [, b]) => (a < b ? -1 : 1))
-    .slice(0, 2)
-    .map(([language]) => language);
+
+  return entries.length === 0
+    ? contributor.interests.split(",").slice(0, 2)
+    : entries
```
Comment (nickytonline) [inline components/molecules/ContributorListTableRow/contributor-list-table-row.tsx:56]: The split on interests is not necessary.

```suggestion
  return (entries.length === 0
    ? contributor.interests.split(",")
    : entries)
```

**Review by nickytonline — CHANGES_REQUESTED** [review]

File: components/molecules/ContributorListTableRow/contributor-list-table-row.tsx [hunk 2]
```diff
@@ -47,12 +47,9 @@ function getLastContributedRepo(pullRequests: DbRepoPR[]) {
...
-  if (entries.length === 0) {
-    return contributor.interests.split(",").slice(0, 2);
-  }
 
   return entries.length === 0
-    ? contributor.interests.split(",").slice(0, 2)
+    ? contributor.interests.split(",")
     : entries
         .sort(([, a], [, b]) => (a < b ? -1 : 1))
         .slice(0, 2)
```
Comment (nickytonline) [inline components/molecules/ContributorListTableRow/contributor-list-table-row.tsx:55]: This will still only slice and sort entries, we need the parentheses.

```diff
-  return entries.length === 0
-    ? contributor.interests.split(",").slice(0, 2)
-    ? contributor.interests.split(",")
-    : entries
+  return (entries.length === 0 ? contributor.interests.split(",") : entries)
    .sort(([, a], [, b]) => (a < b ? -1 : 1))
    .slice(0, 2)
    .map(([language]) => language);
```

**Review by nickytonline — CHANGES_REQUESTED** [review]

**Review by brandonroberts — APPROVED** [review]

**Review by nickytonline — APPROVED** [review]
:shipit:
