### PR TITLE
fix: now some divs on main page are aside elements

### LINKED ISSUE #3016: Bug: Several areas on homepage which have no semantic meaning
There are several areas on the home page such as Top Contributors, Repositories, etc. which are currently in divs. It'd make more sense to have them as asides with a label.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

This fix came about while writing some E2E tests. Now that they have semantic meaning, it's easier to find them in an E2E test.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #3016

## Steps to QA

1. Go to the home page and you should still see all the relevant areas like Top Contributors, Repositories etc.

CleanShot 2024-03-22 at 14 52 43

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

File: components/molecules/AnnouncementCard/announcement-card.tsx [hunk 1]
```diff
@@ -8,8 +8,13 @@ interface AnnouncementCardProps {
   url: string;
 }
 const AnnouncementCard = ({ title, description, bannerSrc, url }: AnnouncementCardProps) => {
+  const announcementId = `announcement-${Date.now()}`;
```
Comment (nickytonline) [inline components/molecules/AnnouncementCard/announcement-card.tsx:11]: The main change in each file is the main element is an `<aside />` now with an `aria-labelled-by` attribute.

**Review by brandonroberts — APPROVED** [review]

**Review by zeucapua — APPROVED** [review]
