### PR TITLE
fix: a11y rule "no-noninteractive-element-interactions"

### LINKED ISSUE #4137: enhancement: a11y rule "no-noninteractive-element-interactions" fails with a warning.
### Describe the bug

[jsx-a11y eslint plugin](https://www.npmjs.com/package/eslint-plugin-jsx-a11y) was recently added to the project and this rule - jsx-a11y/no-noninteractive-element-interactions - fails with a warning.

This issue offers more context: https://github.com/open-sauced/app/issues/2264

### Steps to reproduce

The following components and files are causing the rule to fail:

1. components/molecules/HighlightInput/highlight-input-form.tsx

### PR DESCRIPTION
**Pull request by Dun-sin**
## Description

This PR fixes the Ally warning caused by jsx-ally, by using buttons to replace p and div elements that have `onClick`

## Related Tickets & Documents

Fixes #4137 

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [ ] Tier 4

### CODE REVIEW

File: components/molecules/HighlightInput/highlight-input-form.tsx [hunk 1]
```diff
@@ -754,14 +754,14 @@ const HighlightInputForm = ({ refreshCallback }: HighlightInputFormProps): JSX.E
...
-                                className="text-light-slate-11 truncate max-w-[14rem] xs:max-w-[16rem] text-xs xs:text-sm cursor-pointer hover:text-orange-600 transition"
+                              <button
+                                className="outline-none bg-none text-light-slate-11 truncate max-w-[14rem] xs:max-w-[16rem] text-xs xs:text-sm cursor-pointer hover:text-orange-600 transition"
                                 onClick={() => {
                                   window.open(suggestion.url, "_blank");
                                 }}
                               >
                                 {suggestion.title}
-                              </p>
+                              </button>
```
Comment (nickytonline) [inline components/molecules/HighlightInput/highlight-input-form.tsx:764]: This does fix the warning, but this is a link so it should be an anchor tag instead of a button with an onClick opening the link. Leverage the `target` prop and retain the outline.

```suggestion
                              <a
                                href={suggestion.url}
                                target="_blank"
                                className="truncate max-w-[14rem] xs:max-w-[16rem] text-xs xs:text-sm"
                              >
                                {suggestion.title}
                              </a>
```

**Review by nickytonline — CHANGES_REQUESTED** [review]

File: components/molecules/HighlightInput/highlight-input-form.tsx [hunk 2]
```diff
@@ -1024,13 +1024,13 @@ const HighlightInputForm = ({ refreshCallback }: HighlightInputFormProps): JSX.E
...
+        <button
           onClick={() => setIsFormOpenMobile(true)}
-          className="p-3 mb-10 -mr-4 text-white rounded-full shadow-lg bg-light-orange-10"
+          className="outline-none p-3 mb-10 -mr-4 text-white rounded-full shadow-lg bg-light-orange-10"
           id="mobile-highlight-create"
         >
           <RxPencil1 className="text-3xl" />
-        </div>
+        </button>
       </Fab>
```
Comment (nickytonline) [inline components/molecules/HighlightInput/highlight-input-form.tsx:1034]: The `<Fab />` component has button in it, so no need to add a button within it. Also, button text was missing.

```suggestion
      <Fab
        className="md:hidden p-3 mb-10 -mr-4 text-white rounded-full shadow-lg bg-light-orange-10"
        onClick={() => setIsFormOpenMobile(true)}
      >
        <span className="sr-only">Create a highlight</span>
        <RxPencil1 className="text-3xl" />
      </Fab>
```

To make these changes, you will also need to modify the `<Fab />` component in https://github.com/Dun-sin/app/blob/d75dc77058d83949e70b60e7a8f5f7f2ae0b2195/components/atoms/Fab/fab.tsx

```diff
- const Fab = ({ position, children, className }: FabProps) => {
+ const Fab = ({ position, children, className, onClick }: FabProps) => {
```

and 

```diff
  return (
-    <button type="button" className={clsx("fixed", getFabPositionStyles(), className)}>
+    <button type="button" onClick={onClick} className={clsx("fixed", getFabPositionStyles(), className)}> 
      {children}
    </button>
  );
```

**Review by nickytonline — CHANGES_REQUESTED** [review]

File: components/molecules/HighlightInput/highlight-input-form.tsx (hunk 2 above)
Comment (Dun-sin) [reply components/molecules/HighlightInput/highlight-input-form.tsx:1034]: Thanks for your help with the right direction, Nicky💪🏾

**Review by nickytonline — APPROVED** [review]
Thanks for making the app more accessible @Dun-sin! :shipit:

**Review by brandonroberts — APPROVED** [review]

**Review by zeucapua — APPROVED** [review]
