### PR TITLE
fix: handle `401` error on collaboration feature

### LINKED ISSUE #1632: Bug: error when submitting collaboration
### Describe the bug

When I try to send a collaboration message to [Nick Taylor](https://insights.opensauced.pizza/user/nickytonline/), I get a 401.

image

### Steps to reproduce

1. Go to [Nick Taylor](https://insights.opensauced.pizza/user/nickytonline/)
2. Click the collaborate option
3. See the error

### Browsers

Chrome

### Additional context (Is this in dev or production?)

production

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by babblebey**
## Description

This Pull Request handles the `401` error that may occus on User collaboration request feature, due to restriction of the feature to only users with upgraded access to open-sauced. It adds a descriptive message to notify a user of the need of an upgraded access to use the feature.

### Changes Made

- Add a check for `statusCode` to error response, then append a new toast that carries required message
- ...and left other error to the default handling in the else block.

```js
// lib\hooks\useUserCollaborations.ts

if (req && req.ok) {
  const response = await req.json();
  toast({ description: "Collaboration request Sent!", title: "Success", variant: "success" });
} else {
  const response = await req?.json();

  // Changes From Here <--- 🍕🍕🍕🍕
  if (response.statusCode === 401) {
    toast({
      description: "You require an upgraded access to use collaboration!",
      title: "Not allowed",
      variant: "danger",
    });
  } else {
    toast({ description: response.message, title: "Error", variant: "danger" });
  }
  //🍕🍕🍕🍕
}
```

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [x] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1632 

## Mobile & Desktop Screenshots/Recordings
[screencast-localhost_3000-2023.09.10-18_03_22.webm](https://github.com/open-sauced/app/assets/25631971/93ae8511-bbff-4c14-8733-836fa0ee8c59)

## Added tests ?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

## [optional] Are there any post-deployment tasks we need to perform?

NA

### CODE REVIEW

**Review by OgDev-01 — APPROVED** [review]
LG 🍕

File: lib/hooks/useUserCollaborations.ts [hunk 1]
```diff
@@ -35,7 +35,15 @@ const useUserCollaborations = () => {
       toast({ description: "Collaboration request Sent!", title: "Success", variant: "success" });
     } else {
       const response = await req?.json();
-      toast({ description: response.message[0], title: "Error", variant: "danger" });
+      if (response.statusCode === 401) {
+        toast({
+          description: "You require an upgraded access to use collaboration!",
```
Comment (jpmcb) [inline lib/hooks/useUserCollaborations.ts:40]:
```suggestion
          description: "You require upgraded access to use collaborations!",
```

**Review by brandonroberts — APPROVED** [review]
