### PR TITLE
fix: now layout toggles are radio buttons

### LINKED ISSUE #3887: Bug: Layout toggle for grid/list view is not accessible
The layout toggle for grid/list view is not accessible. The "buttons" are currently divs, so they are not focusable. They should probably be radio buttons.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now the grid layout toggle options are radio buttons. I also added some E2E tests for this.

## Related Tickets & Documents

Fixes #3887

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-08-08 at 11 04 18

**After**

CleanShot 2024-08-08 at 11 05 11

## Steps to QA

1. Go to any page with the layout toggle, e.g. `/explore/topic/typescript/contributors/filter/recent?range=30`
2. Use the tab key on the page to tab to the focusable elements on the page. Notice each layout option receives focus now.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

File: components/atoms/LayoutToggle/layout-toggle.tsx [hunk 1]
```diff
@@ -16,26 +16,32 @@ const LayoutToggle = ({ value, onChange }: LayoutToggleProps) => {
 
   return (
     <div className="flex h-8 border rounded-lg shadow-xs w-28 p-[1px] text-light-slate-9">
-      <div
+      <button
```
Comment (nickytonline) [inline components/atoms/LayoutToggle/layout-toggle.tsx:19]: This could be an actual radio button, but for the time being with how it's styled, I opted for the `role="radio` with `aria-checked`.

**Review by jpmcb — APPROVED** [review]

**Comment by BekahHW** [comment]
@nickytonline not a blocker, but the dashboard outline gets cut off (I'm on chrome)

image

**Review by BekahHW — APPROVED** [review]
