### PR TITLE
fix: pr overviews in repo table now accurate

### LINKED ISSUE #2097: Bug: PR overview not adding up
### Describe the bug

In some cases, PR overview percentage numbers do not add up to 100%.

### Steps to reproduce

For OpenSauced docs on this [insight page](https://app.opensauced.pizza/pages/BekahHW/230/repositories), it adds up to 92%. Visually, you can see that the line doesn't extend as far as the repo above. 

92% of 12 is 11. We currently have one in draft, so I would guess that for some reason, the gray part of the line isn't rendering.  

You'll notice from the full image that the gray line _does_ render on intro, though. 

image

image

image

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR fixes the repo table pr velocity chart display i inaccuracy issue

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
fixes #2097 

### Before
image

### After
image

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Comment by nickytonline** [comment]
There's a before image. Do you have an after image to compare @OgDev-01?

File: components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx [hunk 1]
```diff
@@ -10,24 +10,29 @@ const PullRequestOverviewChartBar: React.FC<PullRequestOverviewChartBarProps & R
...
-            : type === "merged"
-            ? "bg-purple-600"
-            : type === "closed"
-            ? "bg-light-red-9"
-            : type === "draft"
-            ? "bg-light-slate-9"
-            : ""
-        }
-    ${percent === 0 && "hidden"}
+        ${getBarColor(type!)}
```
Comment (nickytonline) [inline components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx:32]: Refactor (blocking): The `!` is not necessary. Avoid changing the type whenever possible. It looks like in the old code, it supported `undefined` as it returned `""` which is the default for the switch case now.

`const getBarColor = (type: string|undefined) => {...}` should do the trick.

File: components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx [hunk 2]
```diff
@@ -10,24 +10,29 @@ const PullRequestOverviewChartBar: React.FC<PullRequestOverviewChartBarProps & R
...
+        ${percent === 0 ? "hidden" : "block"}
         transition-all shrink-0 duration-500 ease-in-out rounded-full`}
-      style={{ width: `${percent}%` }}
+      style={{ width: `${Math.round(percent!)}%` }}
```
Comment (nickytonline) [inline components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx:35]: This appears to be the actual fix?

**Review by nickytonline — CHANGES_REQUESTED** [review]

File: components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx [hunk 3]
```diff
@@ -58,40 +63,40 @@ const PullRequestOverviewChart: React.FC<PullRequestOverviewChartProps> = ({
...
       {/* Merged */}
-      {merged && merged > 0 && (
+      {merged && merged > 0 ? (
         <PullRequestOverviewChartBar
           onMouseOver={() => setOverviewDetails({ type: "merged", percent: merged })}
           percent={getPercentage(merged)}
           type="merged"
         />
-      )}
+      ) : null}
```
Comment (OgDev-01) [inline components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx:81]: This was the actual fix... for some reasons, the `&&` condition renders a `"0"` in the dom for all `0%` type.

File: components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx (hunk 2 above)
Comment (OgDev-01) [reply components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx:35]: This is just a small improvement to remove decimal points from the percent in the markup styles

Comment (jpmcb) [reply components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx:35]: If the intent is to have all lines add up to 100%, there are edge cases here that won't be accounted for. For example:

```js
console.log(
    Math.round(50.01),
    Math.round(49.99 / 3),
    Math.round(49.99 / 3),
    Math.round(49.99 / 3)
);
// 50 17 17 17
```

which adds up to 101.

Also, this will drop any precision on 0 below `0.5` which will cause those parts to not render:

```js
console.log(Math.round(0.4));
// 0
```

---

We may want to consider adding additional precision onto these calculations if we care about having all parts render (unless it is truly 0) and we want it to all add up to 100

Comment (jpmcb) [reply components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx:35]: > This is just a small improvement to remove decimal points from the percent in the markup styles

Makes sense. And if we're going for more or less "close" to adding up to 100 and we're ok dropping percents below `0.4`, then we'll just want to be aware of these edge cases or account for them if that's unacceptable from the design perspective.

File: components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx (hunk 3 above)
Comment (nickytonline) [reply components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx:81]: It's because `draft` is `0` which is falsy, so it stops evaluating the rest and you end up with a `0`.

File: components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx (hunk 1 above)
Comment (nickytonline) [reply components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx:32]: nit: Since this is not part of the fix, consider this for another PR as it's not related to the fix.

**Review by nickytonline — APPROVED** [review]
Left some comments, but this is good to ship. :shipit:

**Review by bdougie — APPROVED** [review]
Tested and looks good in app

File: components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx (hunk 2 above)
Comment (OgDev-01) [reply components/atoms/PullRequestOverviewChart/pull-request-overview-chart.tsx]: reverted the change for now since the previous one broke nothing so we can move on. will revisit another time .

Thanks for the observations 👍
