### PR TITLE
fix: match graph tooltip color with graph nodes

### LINKED ISSUE #1875: Bug: Hover tooltips in repo/contributors graph should match color of repo/user block
### Describe the bug

The hover tooltips in repo/contributors graph should match colour of repo/user block.

### Steps to reproduce

1. Navigate to a list activity page, e.g. https://app.opensauced.pizza/lists/04a518a0-87f7-47ad-89e9-784f4b376941/activity
2. Hover over a repository in the graph.
3. Notice the little square in the hover tooltip is not the same colour as the same as the square (repo/contributor) that it's hovering over.

CleanShot 2023-10-11 at 16 44 56

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR fixes the issue with graph tooltip color inconsistency

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents
closes #1875

### Before
https://github.com/open-sauced/app/assets/62995161/e1aa596b-55cb-464f-af45-d8a5153dc573

### After

https://github.com/open-sauced/app/assets/62995161/b3cf346d-55cc-4bbb-9e70-cc631d739959

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

**Review by nickytonline — COMMENTED** [review]
As discussed, if you can incorporate the 400 values of the Tailwind palette suggested by @isabensusan, only using from orange to rose, then this is good to go.

https://tailwindcss.com/docs/customizing-colors

**Comment by OgDev-01** [comment]
Update: here is a combination of the 400 values from tailwind palette
image

File: lib/utils/color-utils.ts [hunk 1]
```diff
@@ -24,3 +24,22 @@ export function stringToHSLAColor({
 
   return `hsla(${h}, ${saturation}%, ${lightness}%, ${alpha})`;
 }
```
Comment (nickytonline) [inline lib/utils/color-utils.ts:26]: The `stringToHSLAColor()` function can be removed since `getGraphColorPalette()` is replacing it.

File: stories/molecules/treemap-prototype/contributor-node.tsx [hunk 2]
```diff
@@ -45,7 +43,7 @@ const NonMemoizedContributorNode = <Datum extends { id: string; value?: number;
       />
       {showLabel && (
         <animated.div
-          className="grid p-3 text-white place-items-start pointer-events-none"
+          className="grid p-3 text-white pointer-events-none place-items-start"
```
Comment (nickytonline) [inline stories/molecules/treemap-prototype/contributor-node.tsx:46]: Is prettier or eslint rearranging the classes? If not, revert the changes as they are not related to the issue.

File: components/molecules/ContributionsTreemap/contributions-treemap.tsx [hunk 3]
```diff
@@ -8,7 +8,8 @@ import type { NodeMouseEventHandler, NodeProps } from "@nivo/treemap";
 
 interface ContributionsTreemapProps {
   data: any;
-  color: string;
+  // loose typing this as i can't find the import for  OrdinalColorScaleConfig<ComputedNodeWithoutStyles<object>> | undefined
+  color: any;
```
Comment (nickytonline) [inline components/molecules/ContributionsTreemap/contributions-treemap.tsx:12]: Refactor (blocking): The type can be pulled from the Treemap props, and then import these

```diff
- import type { NodeMouseEventHandler, NodeProps } from "@nivo/treemap";
+ import type { NodeMouseEventHandler, NodeProps, TreeMapCommonProps } from "@nivo/treemap";
+ import { Datum } from "@nivo/line";
```

```suggestion
  color: TreeMapCommonProps<Datum>["colors"];
```

File: pages/lists/[listId]/activity.tsx [hunk 4]
```diff
@@ -125,7 +126,7 @@ const ListActivityPage = ({ list, numberOfContributors, isError, activityData }:
       {isError ? (
         <Error errorMessage="Unable to load list activity" />
       ) : (
-        <div className="lg:grid lg:grid-cols-2 lg:grid-rows-2 gap-4 flex flex-col">
+        <div className="flex flex-col gap-4 lg:grid lg:grid-cols-2 lg:grid-rows-2">
```
Comment (nickytonline) [inline pages/lists/[listId]/activity.tsx:129]: Refactor (blocking): This isn't eslint rearranging these. There are also other changes like this below.

File: stories/molecules/treemap-prototype/contributor-node.tsx [hunk 5]
```diff
@@ -54,13 +52,16 @@ const NonMemoizedContributorNode = <Datum extends { id: string; value?: number;
...
         >
           <div className="grid gap-x-2" style={{ gridTemplateColumns: "auto 1fr", gridTemplateRows: "auto auto" }}>
-            <img
-              className="col-start-1 col-span-1 row-span-2"
-              src={avatarURL}
-              width="42"
-              height="42"
-              style={{ display: "block", borderRadius: "50%", border: "solid 2px white", flexShrink: 0, flexGrow: 0 }}
-            />
+            <picture>
```
Comment (nickytonline) [inline stories/molecules/treemap-prototype/contributor-node.tsx:55]: Refactor (blocking): No need for the [picture element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/picture) at the moment as we only have one source for an image.

**Review by nickytonline — CHANGES_REQUESTED** [review]
This is looking good @OgDev-01. Just some change requests.

File: stories/molecules/treemap-prototype/contributor-node.tsx (hunk 5 above)
Comment (OgDev-01) [reply stories/molecules/treemap-prototype/contributor-node.tsx:55]: Added that to fix nextjs native `img` tag warning https://nextjs.org/docs/messages/no-img-element

Comment (nickytonline) [reply stories/molecules/treemap-prototype/contributor-node.tsx:55]: In their example, they use it with source and image tags. In our case we only have one image so it doesn't make sense even though it gives a warning. The img tag could become a Next Image instead.

File: components/molecules/ContributionsTreemap/contributions-treemap.tsx (hunk 3 above)
Comment (OgDev-01) [reply components/molecules/ContributionsTreemap/contributions-treemap.tsx:12]: Thanks 🍕

File: pages/lists/[listId]/activity.tsx (hunk 4 above)
Comment (OgDev-01) [reply pages/lists/[listId]/activity.tsx]: Its a vscode extension i have enabled... i've disabled for this project👍

**Review by nickytonline — APPROVED** [review]
Thanks for making the changes @OgDev-01!

:shipit:
