### PR TITLE
fix: removed GitHub avatar when loading user profile avatars

### LINKED ISSUE #1780: Bug: GitHub Avatar Flashes while paging users in grids
### Describe the bug

Currently when paging through a grid with users, you'll see the GitHub account avatar appear and then get replaced with the user's avatar. The effect is a bit jarring.

### Steps to reproduce

1. Go to a page with a grid and start paging through the grid, e.g. http://localhost:3000/lists/2afc5e31-2925-4030-8818-abfaecdbd174/contributors
2. Notice the jarring effect from GitHub avatar to the user's avatar.

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

When paging through users in a grid, there was a flash of the GitHub avatar while loading a user's avatar. This isn't necessary as the user will always have an avatar.

**Before**

https://github.com/open-sauced/app/assets/833231/be4ed330-94f4-44c0-9a39-40341e631630

**After**

CleanShot 2023-10-02 at 15 56 13

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1780

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [x] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

File: components/molecules/CollaborationCard/collaboration-card.tsx [hunk 1]
```diff
@@ -5,7 +5,7 @@ import { getAvatarByUsername } from "lib/utils/github";
 import Button from "components/atoms/Button/button";
 
 export interface CollaborationRequestObject extends React.ComponentProps<"div"> {
-  requestor: DbUser | undefined;
```
Comment (nickytonline) [inline components/molecules/CollaborationCard/collaboration-card.tsx:8]: This is fine as `DbUser` only. It had a union with `undefined` so that it would work with Storybook. Now Storybook uses a mocked requestor user.

File: components/molecules/ContributorHighlight/contributor-highlight-card.tsx [hunk 2]
```diff
@@ -148,7 +148,8 @@ const ContributorHighlightCard = ({
     ) {
       const { apiPaths } = generateRepoParts(highlight.highlightLink);
       const { repoName, orgName, issueId } = apiPaths;
-      const repoIcon = getAvatarByUsername(orgName, 60);
+      // default to the GitHub avatar if we can't find the avatar for the organization.
```
Comment (nickytonline) [inline components/molecules/ContributorHighlight/contributor-highlight-card.tsx:151]: I can extract this into `getAvatarByOrgName` and default to `"github"` it it's `null`, but it's only in two places at the moment, and I'm also not sure why the org name is not available in these two scenarios.

**Review by brandonroberts — APPROVED** [review]

**Review by OgDev-01 — APPROVED** [review]
LG
