### PR TITLE
fix: h1-h6 base style using CSS from .tracking-tight

### LINKED ISSUE #2141: Bug: Heading typography improvements
Chatting with @isabensusan today, we'd like to see headings use a base style from `.tracking-tight`.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Chatted with @isabensusan this morning and we want to have h1-h6 elements have a base style of the CSS generated from `.tracking-tight`.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [x] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2141

## Mobile & Desktop Screenshots/Recordings

The before is the first few seconds then see it change to the fix. It's anywhere ther is an h1-h6. This is just one example.

CleanShot 2023-11-14 at 19 10 07

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/ListHeader/list-header.tsx [hunk 1]
```diff
@@ -44,7 +44,7 @@ const ListHeader = ({ name, isPublic, listId, isOwner, numberOfContributors }: L
         </div>
         <div className="flex flex-col justify-center p-2 header-info grow">
           <div className="flex gap-2">
-            <Title level={1} className="!text-2xl font-semibold tracking-tight text-slate-900">
```
Comment (nickytonline) [inline components/ListHeader/list-header.tsx:47]: `tracking-tight` is removed here and in the other files below, because the base style handles it now.

**Review by OgDev-01 — APPROVED** [review]

**Review by brandonroberts — APPROVED** [review]
