### PR TITLE
fix: now you can navigate back to the previous page from a user profile page

### LINKED ISSUE #2313: Bug: can't navigate back from user profiles to previous page
### Describe the bug

When navigating from any page to a user profile, if you click on the "back" button on the browser, the paltform doesn't go back to the previous page but rather reloads the user profile.

Reported by Jesse from Xebia:

> When I click a user in the contributors graph above, I'm taken to their profile, the back button won't work to go back to the list, looks like there is an additional redirect added to the history:

https://github.com/open-sauced/app/assets/27322879/bf50f22b-a552-44a9-9992-7e7806aaac3c

### Steps to reproduce

1. Go to the Highlights page 
2. Click on any user profile's link
3. Click "back" on your browser

Expected behaviour would be for the page to go back to Highlights, but it only reloads the user profile.

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by nickytonline**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2313

## Mobile & Desktop Screenshots/Recordings

**Before**

https://github.com/open-sauced/app/assets/27322879/bf50f22b-a552-44a9-9992-7e7806aaac3c

**After**

https://github.com/open-sauced/app/assets/833231/6b4825d0-8098-4014-ba51-1d9f3865017f

## Steps to QA

1. Ensure you're logged in.
2. Go to a lists's contributors, e.g. http://localhost:3000/lists/14ad90aa-fba8-4521-bafd-167490091b13/contributors
3. Click on the avatar or username of the contributor in the grid.
4. Their user profile loads
5. Click the browser back button.
6. The list's contributors page loads.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/organisms/ContributorProfileTab/contributor-profile-tab.tsx [hunk 1]
```diff
@@ -94,32 +94,16 @@ const ContributorProfileTab = ({
...
 
-  const currentTab = (
-    (Object.keys(tabs).includes(tab as string) && tab) || hasHighlights ? "highlights" : "contributions"
-  ) as TabKey;
   function onTabChange(value: string) {
     const tabValue = value as TabKey;
     setQueryParams({ tab: tabValue } satisfies QueryParams);
   }
 
-  useEffect(() => {
```
Comment (nickytonline) [inline components/organisms/ContributorProfileTab/contributor-profile-tab.tsx:110]: The use effect kept adding the query param to the browser history. This is not necessary. We can set a default tab even if it's not in the URL.

**Review by brandonroberts — APPROVED** [review]

**Review by bdougie — APPROVED** [review]
