### PR TITLE
fix: now StarSearch remains visible on smaller screens in the top menu

### LINKED ISSUE #3371: Feature: Make Star Search feature visible on mobile for other pages
### Suggested solution

When on mobile, there's no easy way to get to StarSearch unless you know how to navigate around to a workspace.

image

image

Suggestion: Use a similar pattern to the Upgrade Banner to show a banner for StarSearch with a link to go to it

image

Pages to show banner:

- Explore
- Highlights
- Repo pages

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now StarSearch remains visible on smaller screens in the top menu.

## Related Tickets & Documents

Fixes #3371 

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-05-13 at 19 08 52

**After**

CleanShot 2024-05-13 at 18 59 27

## Steps to QA

1. Go to any page and resize it to a small size.
2. Notice StarSearch remains in the menu.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

**Review by jpmcb — APPROVED** [review]

**Review by bdougie — APPROVED** [review]
This is a quick fix but I'd love to come back to this on another pass post launch @isabensusan

File: components/shared/AppSidebar/AppSidebar.tsx [hunk 1]
```diff
@@ -214,11 +214,6 @@ export const AppSideBar = ({ workspaceId, hideSidebar, sidebarCollapsed }: AppSi
                 url={`/explore/topic/${userInterest}/dashboard/filter/recent`}
                 icon={<Squares2X2Icon className="w-5 h-5 text-slate-400" />}
               />
-              <SidebarMenuItem
```
Comment (nickytonline) [inline components/shared/AppSidebar/AppSidebar.tsx:217]: This is no longer required since it's in the top menu again on smaller screens
