### PR TITLE
fix: language interests are accessible now via keyboard

### LINKED ISSUE #2366: Bug: language interests are not accessible on the user settings page
1. Ensure you're logged in
2. Go to the settings page
3. Use the tab key to navigate the form. When you get to the interests section, notice that if you tab, it skips all interests and gives focus to the Update Interests button.

https://github.com/open-sauced/app/assets/833231/be28dc53-71a4-4ff1-9ca2-48b1cf315f19

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Originally, there was a `<LanguagePill />` component who's parent element was a div with an onclick.

Now there is a `<LanguagePill />` component which is just a pill, and now there is also a `<LanguageSwitch />` which is accessible.

The `<LanguageSwitch /> is used everywhere the `<LanguagePill />` was used and the new `<LanguagePill />` component is used on the user profile page where a `<Link />` wraps it.

Note that the icons in the language pills no longer have alt text as these icons are decorative. I've set them to blank alt text to represen that.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2366

## Mobile & Desktop Screenshots/Recordings

Visually it'll look the same, so you can view them in Storybook:
- [LanguageSwitch component](https://deploy-preview-2365--design-insights.netlify.app/?path=/docs/components-shared-languageswitch--docs)
- [LanguagePill component](https://deploy-preview-2365--design-insights.netlify.app/?path=/docs/components-shared-languagepill--docs)

**Before**

https://github.com/open-sauced/app/assets/833231/be28dc53-71a4-4ff1-9ca2-48b1cf315f19

https://github.com/open-sauced/app/assets/833231/057353e0-8438-41f1-86de-8df529d95466

**After**

https://github.com/open-sauced/app/assets/833231/410a58e7-c874-4ab0-92fa-5040ef1d18bd

CleanShot 2023-12-18 at 09 49 13

## Steps to QA
1. Ensure you're logged in
2. Go to the settings page
3. Use the tab key to navigate the form. When you get to the interests section, each interest you tab to gets a focus state and if you press the space bar, it selects that interest.
4. If you tab to the update interests button and press the spacebar, it'll update your interests.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [x] 📕 storybook
- [ ] 🙅 no documentation needed

### CODE REVIEW

File: components/molecules/ContributorProfileInfo/contributor-profile-info.tsx [hunk 1]
```diff
@@ -178,8 +178,8 @@ const ContributorProfileInfo = ({
               </Title>
               <div className="flex gap-1.5 flex-wrap">
                 {interestArray.map((interest, index) => (
-                  <Link href={`/${interest}/dashboard/filter/recent`} key={index}>
-                    <LanguagePill key={index} topic={interest} />
+                  <Link href={`/${interest}/dashboard/filter/recent`} key={index} className="rounded-3xl">
```
Comment (nickytonline) [inline components/molecules/ContributorProfileInfo/contributor-profile-info.tsx:181]: I added rounded-3xl here so that the focus state takes the shape of the pill.

File: styles/globals.css [hunk 2]
```diff
@@ -26,7 +26,8 @@ h6 {
 input[type="checkbox"]:focus-visible,
 [role="checkbox"]:focus-visible,
 [role="radio"]:focus-visible,
-[role="combobox"]:focus-visible {
+[role="combobox"]:focus-visible,
+[role="switch"]:focus-visible {
```
Comment (nickytonline) [inline styles/globals.css:30]: This allows for switches to keep the uniform focus styling we've been working on.

**Review by jpmcb — COMMENTED** [review]
Maybe a different issue, but are we worries about the accessibility of this white on orange color palette:

Screenshot 2023-12-18 at 8 23 23 AM

Ran this through firefox's accessibility tool real quick and it pops up as inaccessible for text standards

**Comment by nickytonline** [comment]
> Maybe a different issue, but are we worries about the accessibility of this white on orange color palette:
> 
> 
> 
> Screenshot 2023-12-18 at 8 23 23 AM
> 
> 
> 
> Ran this through firefox's accessibility tool real quick and it pops up as inaccessible for text standards

Yeah, that's a separate issue in regards to colour contrast. This issue was specific to not being able to tab or have focus states.

**Review by OgDev-01 — APPROVED** [review]
:pizza:

**Review by jpmcb — APPROVED** [review]
