### PR TITLE
fix: now the contributor card user profile link no longer affects the OSCR login flow

### LINKED ISSUE #3891: Bug: Contributor Card link conflicts with OSCR login button action
This isn't an issue with the OSCR component, but rather the ContributorCard component.

CleanShot 2024-08-08 at 11 48 46

There's a good chunk of the card that is wrapped in a link that goes to the user's profile. It makes more sense to have the link surrounding the avatar and username only.

### PR DESCRIPTION
**Pull request by nickytonline**
## Related Tickets & Documents

Fixes #3891

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-08-08 at 11 48 46

**After**

CleanShot 2024-08-08 at 14 06 18

## Steps to QA

1. Go to any repo contributor page logged out.
2. Click on any of the lock buttons on any contributor card in the grid.
3. Notice it logs you in and you stay on the same page with OSCRs viewable instead of being redirected to the associated user profile page.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

File: components/organisms/ContributorCard/contributor-card.tsx [hunk 1]
```diff
@@ -50,42 +50,44 @@ const ContributorCard = ({ className, contributor, topic, repositories, range, s
     <Card className={className && className}>
       <div className="flex flex-col gap-3">
         <div className="flex items-center justify-between w-full gap-2">
-          <Link href={`/u/${username}`} as={`/u/${username}`}>
-            <div className="flex items-center gap-2">
+          <div className="flex items-center gap-2">
+            <Link href={`/u/${username}`} as={`/u/${username}`}>
```
Comment (nickytonline) [inline components/organisms/ContributorCard/contributor-card.tsx:54]: TLDR;, the link was wrapping too much so clicking the OSCR login button also clicked the link which caused the user to navigate to the profile page associated to the contributor card they clicked on.

Now the link for the user profile only wraps the avatar and the username.

**Review by brandonroberts — APPROVED** [review]

**Review by jpmcb — APPROVED** [review]
