### PR TITLE
fix: now feature flags can be used in middleware

### LINKED ISSUE #2466: Bug: Retrieving feature flags in middleware throws error
Retrieving feature flags in the app works, but I was loading them in middleware for the work in #2437, and kept getting errors.

```
Error fetching feature flags  [PostHogFetchNetworkError: Network error while fetching PostHog] {
  error:  [AxiosError: There is no suitable adapter to dispatch the request since :
- adapter xhr is not supported by the environment
- adapter http is not available in the build] {
  message: 'There is no suitable adapter to dispatch the request since :\n- adapter xhr is not supported by the environment\n- adapter http is not available in the build',
  name: 'AxiosError',
  code: 'ERR_NOT_SUPPORT'
},
  name: 'PostHogFetchNetworkError'
}
```

I realized that the Posthog client doesn't appear to work in middleware, so we should opt for a fetch call instead which will work everywhere. see https://posthog.com/tutorials/nextjs-bootstrap-flags.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Prior to this change, retrieving feature flags did not work in middleware, now they do

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2466
Relates to #2437

## Steps to QA

1. For @open-sauced/engineering, ensure you still see the new side bar when you're logged in.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: lib/utils/server/feature-flags.ts [hunk 1]
```diff
@@ -1,17 +1,22 @@
...
+    },
+    body: JSON.stringify({
+      api_key: process.env.NEXT_PUBLIC_POSTHOG_ID,
+      distinct_id: userId,
+    }),
+  };
 
-    { host: "https://app.posthog.com" }
+  const response = await fetch(
+    "https://app.posthog.com/decide?v=3", // or eu
```
Comment (jpmcb) [inline lib/utils/server/feature-flags.ts:16]: Non-blocking: what's `or eu`? 🤔

**Review by jpmcb — APPROVED** [review]

File: lib/utils/server/feature-flags.ts (hunk 1 above)
Comment (nickytonline) [reply lib/utils/server/feature-flags.ts:16]: Me not knowing how to type lol. I'll remove it.

**Review by OgDev-01 — APPROVED** [review]
