### PR TITLE
fix: No more 404 errors in the browser console

### LINKED ISSUE #1950: Bug: 404 errors in the browser console with the message "You are not following this user"
### Describe the bug

I've been seeing this error pop up multiple times if you go to the feed page. Not sure if it's happening elsewhere.

### Steps to reproduce

1. Go to app.opensauced.pizza/feed
2. Open up the browser dev tools and go to the console tab.
3. Notice the 404 errors.

CleanShot 2023-10-19 at 09 54 53

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by OgDev-01**
## Description
This PR fixes the issue with multiple calls being sent to the api even when they are not currently needed. the `useFollowUser` call has been made to only fetch when a highlight dropdown is opened, and as a result the calls won't kick in as it use to before this changes until a user clicks on a single highlight more menu option.

### Notes
I also removed the top users panel entirely from the DOM if we are on mobile to prevent making a call to check for user follows

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #1950

### Before

https://github.com/open-sauced/app/assets/62995161/894e6f7a-7efb-400d-bf7b-697b25f3c288

### After 

https://github.com/open-sauced/app/assets/62995161/56474dd1-3dff-4241-b78f-b5949f69b8e6

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: pages/feed/index.tsx [hunk 1]
```diff
@@ -78,6 +79,8 @@ const Feeds: WithPageLayout<HighlightSSRProps> = (props: HighlightSSRProps) => {
 
   const { data: followersRepo } = useFetchFollowersHighlightRepos();
 
+  const isDesktop = useMediaQuery("(min-width: 1280px)");
```
Comment (OgDev-01) [inline pages/feed/index.tsx:82]: Using this to prevent the top user panel component from rendering on mobile

This also prevents it from checking for following on mobile and tab

File: pages/feed/index.tsx [hunk 2]
```diff
@@ -212,11 +215,13 @@ const Feeds: WithPageLayout<HighlightSSRProps> = (props: HighlightSSRProps) => {
                 />
               </div>
             )}
-            <TopContributorsPanel
-              loggedInUserLogin={loggedInUser?.login ?? ""}
-              loggedInUserId={loggedInUser?.id ?? undefined}
-              refreshLoggedInUser={refreshLoggedInUser}
-            />
+            {isDesktop && (
```
Comment (OgDev-01) [inline pages/feed/index.tsx:218]: This also prevents it from checking for following on mobile and tab

**Review by nickytonline — APPROVED** [review]
I tested this locally @OgDev-01 and the errors no longer appear. One small non-blocking refactor request.

:shipit:

**Review by brandonroberts — APPROVED** [review]
