### PR TITLE
fix: now main index page handles redirects in middleware

### LINKED ISSUE #1918: Index page should handle redirects via SSR
Currently the index page handles redirects on the client-side, i.e. https://github.com/open-sauced/app/blob/bf1228606bd95fe0dab290c77db0075159e558fa/pages/index.tsx 

These types of redirects are better handled on the server-side. There's no need to load a page and then redirect. We can redirect immediately via SSR.

It could potentially even be a Netlify function handling this redirect logic.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now redirects on the main route, i.e. `/` are handled in middleware. I've left fallbacks in the actual page to redirect to `/feed` if something goes wrong.

Scenarios:
Not logged in: Redirected to `/feed`
Logged in (not onboarded): Redirected to `/feed`
Logged in (onboarded): Redirected to `/hub/insights`.

Please take it for a test run to ensure the scenarios above work for you as well. For not onboarded you can debug and fake it or reset your onboarded status in the dev database.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Mobile & Desktop Screenshots/Recordings

Fixes #1918

## Added tests?

- [ ] 👍 yes
- [x] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: middleware.ts [hunk 1]
```diff
@@ -8,13 +8,40 @@ import { pathToRegexp } from "path-to-regexp";
...
 const pathsToMatch = [
+  "/",
   "/hub/insights/:path*",
   "/feed/",
   "/user/notifications",
   "/user/settings",
   "/account-deleted"
 ];
 
+const NO_ONBOARDING_PAYLOAD = {
```
Comment (nickytonline) [inline middleware.ts:19]: Similar to what's in https://github.com/open-sauced/app/blob/d7a69fd8c648892d80a51112730226091b544b10/lib/hooks/useSession.ts#L14-L30

File: pages/index.tsx [hunk 2]
```diff
@@ -1,41 +1,23 @@
...
-      if (currentUser?.data?.session && onboarded === true) {
-        redirect("/hub/insights");
-      } else {
-        redirect("/feed");
-      }
-    }
-
-    getAccess();
-  }, [router, onboarded]);
+export const getServerSideProps = async () => {
```
Comment (nickytonline) [inline pages/index.tsx:4]: You should never get to the actual page because of middleware, but if for some reason you do, I've added default redirects to `/feed`.

**Review by bdougie — APPROVED** [review]
LGTM

Would love to address where we redirect to based on persona

onboarded maintainer - redirect to insights pages
all other users - feed or future explore page.

**Review by brandonroberts — APPROVED** [review]
