### PR TITLE
fix: now the highlight input form closes only if you press ESC or click the close button

### LINKED ISSUE #2256: Bug: Spell Checkers Close the Highlight Input Form
### Describe the bug

Using a spell checker like like the Office 365 spell checker causes the highlight input form to close when a word is corrected.

### Steps to reproduce

The compose window for a new highlight doesn't play nice with the Office 365 spelling checker. https://microsoftedge.microsoft.com/addons/detail/microsoft-editor-spellin/hokifickgkhplphjiodbggjmoafhignh

1. Navigate to https://app.opensauced.pizza/feed
2. The Office 365 spell checker goes into action and then the highlight input form disappears.

https://github.com/open-sauced/app/assets/833231/531733c7-38a5-4d6a-aaf7-649174d95b5a

Thanks for reporting this @jessehouwing

### Browsers

_No response_

### Additional context (Is this in dev or production?)

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Now the Highlight form only closes if you press <kbd>ESC</kbd>, click the close button, or submit a highlight successfully.

## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2256
## Mobile & Desktop Screenshots/Recordings

CleanShot 2023-12-04 at 16 47 50

## Steps to QA

1. Ensure you're logged in
2. Go to the feed, https://deploy-preview-2257--oss-insights.netlify.app/feed
3. Create a new hightlight.
4. Click outside the modal. Notice the modal doesn't close.
5. Press the <kbd>ESC</kbd> key. The modal closes.
6. Repeat steps 1-4. Click the close button at the top right of the modal. The modal closes.
7. Repeat steps 1-4. Create a new highlight with the required fields. Click the post button.
8. The modal closes.

I don't have the Office 365 spell checker @jessehouwing, but if you don't mind taking this for a spin real quick to confirm it's all good with your spell checker, it'd be appreciated. (https://deploy-preview-2257--oss-insights.netlify.app/feed)

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/molecules/HighlightInput/highlight-input-form.tsx [hunk 1]
```diff
@@ -528,13 +528,13 @@ const HighlightInputForm = ({ refreshCallback }: HighlightInputFormProps): JSX.E
...
-      <Dialog
-        onOpenChange={() => {
-          setIsDivFocused(false);
-        }}
-        open={isDivFocused}
-      >
-        <DialogContent className="p-4 w-full md:w-[40rem] xs:w-96 max-h-[80vh] overflow-y-scroll">
+      <Dialog open={isDivFocused}>
+        <DialogContent
+          onEscapeKeyDown={() => {
```
Comment (nickytonline) [inline components/molecules/HighlightInput/highlight-input-form.tsx:533]: I added the <kbd>ESC</kbd> key to make this more accessible on top of just being able to close the modal via the top right close button.

File: components/molecules/HighlightInput/highlight-input-form.tsx [hunk 2]
```diff
@@ -528,13 +528,13 @@ const HighlightInputForm = ({ refreshCallback }: HighlightInputFormProps): JSX.E
           </div>
         </div>
       </div>
-      <Dialog
-        onOpenChange={() => {
-          setIsDivFocused(false);
-        }}
```
Comment (nickytonline) [inline components/molecules/HighlightInput/highlight-input-form.tsx:534]: We don't need this. It actually is problematic in general. If you have a modal open, it will close automatically if you click accidentally outside the modal.

**Review by brandonroberts — APPROVED** [review]
🖱️

**Review by OgDev-01 — APPROVED** [review]
