### PR TITLE
fix: now workspace settings and new page have a fixed footer for CTAs

### LINKED ISSUE #2924: Bug: Button that saves a repository to workspace floats to bottom of page
### Describe the bug

The button floats to bottom of page when scrolling instead of staying close to the input with the lost of repositories to be added. 

As shown below:
Screenshot 2024-03-12 at 13 35 31

### Steps to reproduce

 1. Go to workspaces tab
 2. Click add a repository
 3. Follow prompts to add a repository
 4. Notice the "update workspace" button floats to the bottom of page when scrolling

### Browsers

Chrome

### Additional context (Is this in dev or production?)

localhost

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

### PR DESCRIPTION
**Pull request by nickytonline**
## What type of PR is this? (check all applicable)

- [ ] 🍕 Feature
- [x] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🎨 Style
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore (Release)
- [ ] ⏩ Revert

## Related Tickets & Documents

Fixes #2924

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-03-20 at 10 08 59

**After**

**Settings Page**

CleanShot 2024-03-20 at 10 07 25

CleanShot 2024-03-20 at 09 55 04

**New Workspace Page**

CleanShot 2024-03-20 at 09 56 01

## Steps to QA

1. Go to your workspace settings page, e.g. /workspaces/some-worspace-id/settings
2. Scroll through the settings.
3. Notice the Update workspace button remains in a fixed footer and content scrolls underneath it.
4. Do the same thing for the create new workspace page, /workspaces/new, and the same behaviour occurs.

## Added to documentation?

- [ ] 📜 README.md
- [ ] 📓 docs.opensauced.pizza
- [ ] 🍕 dev.to/opensauced
- [ ] 📕 storybook
- [x] 🙅 no documentation needed

### CODE REVIEW

File: components/Workspaces/WorkspaceLayout.tsx [hunk 1]
```diff
@@ -11,9 +11,10 @@ interface WorkspaceLayoutProps {
   workspaceId: string;
   banner?: React.ReactNode;
   children: React.ReactNode;
+  footer?: React.ReactNode;
```
Comment (nickytonline) [inline components/Workspaces/WorkspaceLayout.tsx:14]: The footer is optional (for now at least), because not all pages that use the workspaces layout need it.

Longterm, the update/create CTAs for insight pages should live in the footer as well @isabensusan to keep things uniform.

File: pages/workspaces/[workspaceId]/settings.tsx [hunk 2]
```diff
@@ -214,7 +214,14 @@ const WorkspaceSettings = ({ workspace, canDeleteWorkspace }: WorkspaceSettingsP
   };
 
   return (
-    <WorkspaceLayout workspaceId={workspace.id}>
+    <WorkspaceLayout
+      workspaceId={workspace.id}
+      footer={
```
Comment (nickytonline) [inline pages/workspaces/[workspaceId]/settings.tsx:219]: The footer prop acts as a slot since React doesn't natively support slots.

File: components/Workspaces/WorkspaceLayout.tsx [hunk 3]
```diff
@@ -36,34 +37,41 @@ export const WorkspaceLayout = ({ workspaceId, banner, children }: WorkspaceLayo
...
+                className="fixed z-50 border-8 border-solid border-black inset-x-0 top-16 w-fit bg-white rounded-r-md shadow-lg p-2"
+              >
+                <LuArrowRightToLine className="w-4 h-4 text-gray-500" />
+              </button>
+            )}
+          </ClientOnly>
+        </div>
+        <div className="relative flex flex-col items-center grow pt-8 md:pt-14 lg:pt-20">
+          {banner}
+          <div className="px-1 sm:px-2 md:px-4 xl:px-16 container w-full min-h-[100px] pb-32">{children}</div>
```
Comment (nickytonline) [inline components/Workspaces/WorkspaceLayout.tsx:67]: I added padding at the bottom so that you can see all the content with the fixed footer and also, it's just nice to have some empty space at the end when scrolling.

File: pages/workspaces/[workspaceId]/settings.tsx [hunk 4]
```diff
@@ -278,7 +277,6 @@ const WorkspaceSettings = ({ workspace, canDeleteWorkspace }: WorkspaceSettingsP
             onUpdateMember={async (memberId, role) => await updateMember(workspace.id, sessionToken, memberId, role)}
             onDeleteMember={async (memberId) => await deleteMember(workspace.id, sessionToken, memberId)}
             members={workspaceMembers}
-            className="z-10"
```
Comment (nickytonline) [inline pages/workspaces/[workspaceId]/settings.tsx:281]: This is no longer required. Relates to #2897.

File: pages/workspaces/[workspaceId]/settings.tsx [hunk 5]
```diff
@@ -237,14 +244,6 @@ const WorkspaceSettings = ({ workspace, canDeleteWorkspace }: WorkspaceSettingsP
               placeholder="Workspace description"
               className="w-full md:w-3/4 max-w-lg"
             />
-            <div className="bg-white sticky-bottom fixed rounded-lg bottom-4 right-0 self-end m-6">
-              <Button
-                variant="primary"
-                className="z-50 flex gap-2.5 items-center cursor-pointer w-min sm:mt-0 self-end"
```
Comment (nickytonline) [inline pages/workspaces/[workspaceId]/settings.tsx:243]: The z-50 is nolonger required along with other z-indices removed in this PR. Undoes what as done in #2864.

**Review by jpmcb — APPROVED** [review]
QA'd - looks great!! 👏🏼

**Comment by isabensusan** [comment]
QA'd it and it looks great!! I'll open a separate ticket to add the same interaction to Repo/Contributor insights

**Review by isabensusan — APPROVED** [review]
