### PR TITLE
fix: style and layout fixes for StarSearch

### LINKED ISSUE #3266: Feature: Make the StarSearch prompt input sticky at the bottom of the page
Make the StarSearch prompt input sticky at the bottom of the page. Currently it's usable, but it'd be nice to have it fixed to the bottom of the page like ChatGPT.

This would be something we could do once we get a decision on removing the footer @isabensusan.

### LINKED ISSUE #3319: Bug: UI disappears after many queries
### Describe the bug

I've been able to reproduce this a couple of times, but I had to keep querying. I think it happens when the scroll is activated on the screen.

https://github.com/open-sauced/app/assets/34313413/917ba897-b5d9-41ed-a295-2866387511a3

### Steps to reproduce

1. go to star search
2. just keep querying until you see it. I think it took me about 9 queries. 

Don't touch the screen while the answer is loading.

### PR DESCRIPTION
**Pull request by nickytonline**
## Description

Some style and layout tweaks for StarSearch including the input prompt being sticky at the bottom of the page now.

@isabensusan, the footer is still there, as per Slack discussions, but if we want to remove it, it's a quick change.

The prompt input is also sticky now on the bottom of the page.

## Related Tickets & Documents

Fixes #3266
Fixes #3319

## Mobile & Desktop Screenshots/Recordings

**Before**

CleanShot 2024-05-02 at 15 13 25

CleanShot 2024-05-02 at 15 18 06

**After**

CleanShot 2024-05-02 at 15 14 51

CleanShot 2024-05-02 at 15 17 25

## Steps to QA

1. Go to `/star-search`
2. Enter a question or click on a sample prompt.

## Tier (staff will fill in)

- [ ] Tier 1
- [ ] Tier 2
- [ ] Tier 3
- [x] Tier 4

### CODE REVIEW

File: components/shared/Drawer.tsx [hunk 1]
```diff
@@ -15,12 +15,20 @@ interface DrawerProps {
   children: React.ReactNode;
   trigger: React.ReactNode;
   showCloseButton?: boolean;
+  asChild?: boolean;
```
Comment (nickytonline) [inline components/shared/Drawer.tsx:18]: I added this prop so that the trigger is the JSX that renders and not the default which is a button.

This was an issue prior to this change because the trigger button we had ended up in another button affecting styling.

File: pages/star-search/index.tsx [hunk 2]
```diff
@@ -79,7 +77,7 @@ export default function StarSearchPage({ userId, bearerToken, ogImageUrl }: Star
   const [chat, setChat] = useState<StarSearchChat[]>([]);
   const inputRef = useRef<HTMLInputElement>(null);
   const [isRunning, setIsRunning] = useState(false);
-  const isMobile = useMediaQuery("(max-width: 576px)");
+  const isMobile = useMediaQuery("(max-width: 768px)");
```
Comment (nickytonline) [inline pages/star-search/index.tsx:80]: I increased the size here to the medium breakpoint because the current scrollable suggestions were outside of the viewport on size larger than the small breakpoint, but smaller than the medium breakpoint.

**Review by BekahHW — APPROVED** [review]
